<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class BangladeshPharmaceuticalSuppliersSeeder extends Seeder
{
    /**
     * Seed the supplier master list. Existing supplier names are preserved.
     */
    public function run(): void
    {
        $suppliers = [
            'Square Pharmaceuticals PLC',
            'Incepta Pharmaceuticals Ltd.',
            'Beximco Pharmaceuticals Ltd.',
            'Eskayef Pharmaceuticals Ltd.',
            'Renata PLC',
            'ACI Limited',
            'ACME Laboratories Ltd.',
            'Opsonin Pharma Ltd.',
            'Aristopharma Ltd.',
            'Healthcare Pharmaceuticals Ltd.',
            'Drug International Ltd.',
            'Beacon Pharmaceuticals PLC',
            'Popular Pharmaceuticals Ltd.',
            'Radiant Pharmaceuticals Ltd.',
            'General Pharmaceuticals Ltd.',
            'The IBN SINA Pharmaceutical PLC',
            'Orion Pharma Ltd.',
            'NIPRO JMI Pharma Ltd.',
            'UniMed UniHealth Pharmaceuticals Ltd.',
            'Navana Pharmaceuticals Ltd.',
            'Ziska Pharmaceuticals Ltd.',
            'Techno Drugs Ltd.',
            'Globe Pharmaceuticals Ltd.',
            'Biopharma Limited',
            'Delta Pharma PLC',
            'Pacific Pharmaceuticals Ltd.',
            'Pharmadesh Laboratories Ltd.',
            'Pharmasia Limited',
            'Euro Pharma Ltd.',
            'Everest Pharmaceuticals Ltd.',
            'Jayson Pharmaceutical Ltd.',
            'Kemiko Pharmaceuticals Ltd.',
            'Kumudini Pharma Ltd.',
            'Labaid Pharma Ltd.',
            'Leon Pharmaceuticals Ltd.',
            'Medicon Pharmaceuticals Ltd.',
            'Medimet Pharmaceuticals Ltd.',
            'Monicopharma Ltd.',
            'Naafco Pharma PLC',
            'Nuvista Pharma Ltd.',
            'One Pharma Ltd.',
            'Orion Infusion Ltd.',
            'OSL Pharma Limited',
            'Rangs Pharmaceuticals Ltd.',
            'Rephco Pharmaceuticals Ltd.',
            'Sharif Pharmaceuticals Ltd.',
            'Silva Pharmaceuticals Ltd.',
            'Somatec Pharmaceuticals Ltd.',
            'Sun Pharmaceutical Bangladesh Ltd.',
            'Synovia Pharma PLC',
            'Team Pharmaceuticals Ltd.',
            'The White Horse Pharmaceuticals Ltd.',
            'UniHealth Limited',
            'Union Pharmaceuticals Ltd.',
            'United Pharmaceuticals Ltd.',
            'Veritas Pharmaceuticals Ltd.',
            'Virgo Pharmaceuticals Ltd.',
            'Zenith Pharmaceuticals Ltd.',
            'Apex Pharma Ltd.',
            'Ambee Pharmaceuticals Ltd.',
            'Asiatic Laboratories Ltd.',
            'Albion Laboratories Limited',
            'Alco Pharma Ltd.',
            'Apollo Pharmaceutical Ltd.',
            'Benham Pharmaceuticals Ltd.',
            'Bristol Pharmaceuticals Ltd.',
            'Central Pharmaceuticals Ltd.',
            'Chemist Laboratories Ltd.',
            'Concord Pharmaceuticals Ltd.',
            'Cosmic Pharma Ltd.',
            'DBL Pharmaceuticals Ltd.',
            'Decent Pharma Laboratories Ltd.',
            'Desh Pharmaceuticals Ltd.',
            'Doctor TIMS Pharmaceuticals Ltd.',
            'Edruc Limited',
            'Ethical Drugs Limited',
            'Gaco Pharmaceuticals Ltd.',
            'Genvio Pharma Ltd.',
            'Gonoshasthaya Pharma Ltd.',
            'Goodman Pharmaceuticals Ltd.',
            'Hallmark Pharmaceuticals Ltd.',
            'Hudson Pharmaceuticals Ltd.',
            'Jenphar Bangladesh Ltd.',
            'Libra Infusions Ltd.',
            'Maks Drug Limited',
            'Marker Pharma Ltd.',
            'Modern Pharmaceuticals Ltd.',
            'Mystic Pharmaceuticals Ltd.',
            'National Drug Co. Ltd.',
            'Nipa Pharmaceuticals Ltd.',
            'Novatek Pharmaceuticals Ltd.',
            'Novo Healthcare and Pharma Ltd.',
            'Novus Pharmaceuticals Ltd.',
            'Pharmik Laboratories Ltd.',
            'Premier Pharmaceuticals Ltd.',
            'Prime Pharmaceuticals Ltd.',
            'Pristine Pharmaceuticals Ltd.',
            'Quality Pharmaceuticals Ltd.',
            'Reman Drug Laboratories Ltd.',
            'Reliance Pharmaceuticals Ltd.',
            'Salton Pharmaceuticals Ltd.',
            'Save Pharmaceuticals Ltd.',
            'Seema Pharmaceuticals Ltd.',
            'Silco Pharmaceutical Ltd.',
            'Skylab Pharmaceuticals Ltd.',
            'SMC Enterprise Ltd.',
            'Sonear Laboratories Ltd.',
            'Sunman-Birdem Pharma Ltd.',
            'Supreme Pharmaceutical Ltd.',
            'Syntho Laboratories Ltd.',
            'UNIDO Pharmaceuticals Ltd.',
            'Unique Pharmaceuticals Ltd.',
            'Walmart Pharma Ltd.',
            'ZAS Corporation',
        ];

        foreach ($suppliers as $name) {
            Supplier::firstOrCreate(['name' => $name], ['is_active' => true]);
        }
    }
}
