<x-app-layout>
<x-slot name="header"><div class="flex items-center justify-between"><h1 class="text-lg font-bold uppercase text-[#4e6c9d]">Dashboard <span class="text-[11px] font-normal text-slate-400">quick overview</span></h1><span class="text-xs text-slate-500">{{ now()->format('d M Y') }}</span></div></x-slot>
<div class="space-y-5">
<section class="grid gap-4 xl:grid-cols-3">
<article class="flex min-h-28 items-center gap-5 bg-[#5792c0] p-4 text-white"><div class="grid h-14 w-14 place-items-center bg-slate-900 text-xs font-bold">AUTO<br>CRM</div><div class="grid flex-1 grid-cols-2 gap-x-6 gap-y-4 text-center text-sm"><div><b class="block text-base">{{ number_format($todaySales,0) }}</b>Target</div><div><b class="block text-base">{{ number_format($todayProfit,0) }}</b>Achieved</div><div><b class="block text-base">{{ number_format($stockPieces) }}</b>Sales</div><div><b class="block text-base">{{ number_format($todayPurchases,0) }}</b>Collection</div></div></article>
<article class="flex min-h-28 items-center gap-5 bg-[#eba10b] p-4 text-white"><div class="grid h-14 w-14 place-items-center rounded-full bg-white/20 text-xl">✦</div><div class="grid flex-1 grid-cols-2 gap-x-6 gap-y-4 text-center text-sm"><div><b class="block text-base">{{ number_format($todayPurchases,0) }}</b>Target</div><div><b class="block text-base">{{ number_format($todaySales,0) }}</b>Achieved</div><div><b class="block text-base">{{ $lowStockCount }}</b>Low Stock</div><div><b class="block text-base">{{ $presentToday }}</b>Collection</div></div></article>
<article class="flex min-h-28 items-center gap-5 bg-[#ed4145] p-4 text-white"><div class="grid h-14 w-14 place-items-center rounded-full bg-white/20 text-xl">⌁</div><div class="grid flex-1 grid-cols-3 gap-x-4 text-center text-sm"><div><b class="block text-base">{{ $activeEmployees }}</b>D. Target</div><div><b class="block text-base">{{ $presentToday }}</b>D. Ach.</div><div><b class="block text-base">{{ number_format($todayProfit,0) }}</b>Collection</div></div></article>
</section>
<section class="grid gap-5 xl:grid-cols-2"><article class="border border-slate-200 bg-white"><div class="flex items-center justify-between border-b px-4 py-3"><h2 class="font-semibold text-[#4e6c9d]">Cheque Summary</h2><a href="{{ route('cheques.index') }}" class="text-xs text-teal-700">View all</a></div><div class="grid grid-cols-4 gap-2 p-3 text-center"><div class="border p-3"><p class="text-xs text-slate-500">In Hand</p><b class="text-3xl text-lime-500">{{ $lowStockCount }}</b></div><div class="border p-3"><p class="text-xs text-slate-500">Deposited</p><b class="text-3xl text-sky-500">0</b></div><div class="border p-3"><p class="text-xs text-slate-500">Honored</p><b class="text-3xl text-orange-400">{{ $presentToday }}</b></div><div class="border p-3"><p class="text-xs text-slate-500">Dishonored</p><b class="text-3xl text-rose-500">0</b></div></div><div class="px-3 pb-4 text-sm text-slate-500">Review pending collections and statuses in Cheques.</div></article><article class="border border-slate-200 bg-white"><div class="border-b px-4 py-3"><h2 class="font-semibold text-rose-500">Collection <span class="text-xs font-normal text-slate-400">month wise</span></h2></div><div class="flex h-40 items-end gap-3 p-5">@foreach($weeklySales as $day)<div class="flex h-full flex-1 flex-col justify-end"><span class="mb-1 text-center text-[10px]">৳{{ number_format($day['total']/1000,0) }}k</span><div class="bg-[#5792c0]" style="height: {{ max(4, round($day['total']/$maxWeeklySale*100)) }}%"></div><span class="mt-2 text-center text-[10px] text-slate-500">{{ $day['label'] }}</span></div>@endforeach</div></article></section>
<section class="grid gap-5 lg:grid-cols-3"><article class="border bg-white p-4"><p class="text-xs uppercase text-slate-500">Available Stock</p><b class="mt-2 block text-2xl text-[#4e6c9d]">{{ number_format($stockPieces) }}</b><p class="mt-1 text-xs text-slate-400">৳{{ number_format($stockValue,2) }} value</p></article><article class="border bg-white p-4"><p class="text-xs uppercase text-slate-500">Low Stock Items</p><b class="mt-2 block text-2xl text-amber-600">{{ $lowStockCount }}</b><a href="{{ route('products.index') }}" class="mt-1 text-xs text-teal-700">Open Item Inventory →</a></article><article class="border bg-white p-4"><p class="text-xs uppercase text-slate-500">Expiry Watch</p><b class="mt-2 block text-2xl text-rose-600">{{ $expiringCount }}</b><p class="mt-1 text-xs text-slate-400">Batches due within 90 days</p></article></section>
<section class="grid gap-5 xl:grid-cols-2">
    <article class="border border-slate-200 bg-white">
        <div class="flex items-center justify-between border-b px-4 py-3"><h2 class="font-semibold text-[#4e6c9d]">⌘ Recent Activities</h2><a href="{{ route('activities.index') }}" class="text-xs text-teal-700">All activities →</a></div>
        <div class="max-h-72 overflow-y-auto"><table class="w-full text-left text-xs"><thead class="sticky top-0 bg-slate-50 text-slate-500"><tr><th class="px-4 py-2">Date &amp; time</th><th class="px-4 py-2">Type</th><th class="px-4 py-2">With / details</th><th class="px-4 py-2">User</th></tr></thead><tbody class="divide-y">@forelse($recentActivities as $activity)<tr><td class="px-4 py-3 whitespace-nowrap">{{ $activity->from_at->format('d M, h:i A') }}</td><td class="px-4 py-3 font-semibold text-sky-700">{{ $activity->type?->name ?: 'Activity' }}</td><td class="px-4 py-3">{{ $activity->activity_with ?: ($activity->remarks ?: '—') }}</td><td class="px-4 py-3 text-slate-500">{{ $activity->user?->name ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-10 text-center text-slate-500">Recent activities will appear here.</td></tr>@endforelse</tbody></table></div>
    </article>
    <article class="border border-slate-200 bg-white">
        <div class="flex items-center justify-between border-b px-4 py-3"><h2 class="font-semibold text-teal-600">⌘ To Do Reminder</h2><a href="{{ route('todos.index') }}" class="text-xs text-teal-700">See all →</a></div>
        <div class="max-h-72 overflow-y-auto"><table class="w-full text-left text-xs"><thead class="sticky top-0 bg-slate-50 text-slate-500"><tr><th class="px-4 py-2">Due</th><th class="px-4 py-2">Type</th><th class="px-4 py-2">With</th><th class="px-4 py-2">Particulars</th><th class="px-4 py-2">Status</th></tr></thead><tbody class="divide-y">@forelse($todoReminders as $todo)<tr><td class="px-4 py-3 whitespace-nowrap {{ $todo->due_at->isPast() ? 'text-rose-600' : '' }}">{{ $todo->due_at->format('d M, h:i A') }}</td><td class="px-4 py-3">{{ $todo->type?->name ?: 'To do' }}</td><td class="px-4 py-3">{{ $todo->task_with ?: '—' }}</td><td class="px-4 py-3">{{ $todo->note ?: '—' }}</td><td class="px-4 py-3 font-semibold {{ $todo->due_at->isPast() ? 'text-rose-600' : 'text-amber-600' }}">{{ ucfirst($todo->status) }}</td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-slate-500">No pending reminders for the next 14 days.</td></tr>@endforelse</tbody></table></div>
    </article>
</section>
<section class="grid gap-5 xl:grid-cols-2">
    <article class="border border-slate-200 bg-white p-4"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold text-rose-500">⌄ Lead Pipeline</h2><a href="{{ route('leads.index') }}" class="text-xs text-teal-700">View leads →</a></div><div class="space-y-2">@forelse($pipelineSummary as $pipeline)<div class="flex items-center justify-between rounded px-3 py-2 text-sm text-white" style="background-color: hsl({{ 205 + ($loop->index * 34) }}, 42%, {{ 48 + ($loop->index % 3 * 8) }}%)"><span>{{ $pipeline->name }}</span><b class="rounded-full bg-slate-900/35 px-2 py-0.5">{{ number_format($pipeline->total) }}</b></div>@empty<p class="py-8 text-center text-sm text-slate-500">Pipeline stages will appear after they are configured.</p>@endforelse</div></article>
    <article class="border border-slate-200 bg-white p-4"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold text-teal-600">◉ Lead Status</h2><a href="{{ route('leads.index') }}" class="text-xs text-teal-700">View leads →</a></div><div class="space-y-3">@php($statusTotal = max(1, $leadStatusSummary->sum('total')))@forelse($leadStatusSummary as $status)<div><div class="mb-1 flex justify-between text-xs"><span class="font-semibold">{{ $status->name }}</span><span>{{ number_format($status->total) }} · {{ number_format($status->total / $statusTotal * 100, 1) }}%</span></div><div class="h-3 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full" style="width: {{ $status->total / $statusTotal * 100 }}%; background-color: {{ $status->badge_color ?: '#4e6c9d' }}"></div></div></div>@empty<p class="py-8 text-center text-sm text-slate-500">Lead status totals will appear after statuses are configured.</p>@endforelse</div></article>
</section>
<section class="grid gap-5 xl:grid-cols-2">
    <article class="border border-slate-200 bg-white"><div class="flex items-center justify-between border-b px-4 py-3"><h2 class="font-semibold text-amber-600">Warm Leads</h2><a href="{{ route('leads.index') }}" class="text-xs text-teal-700">See all →</a></div><table class="w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500"><tr><th class="px-4 py-2">Name</th><th class="px-4 py-2">Contact</th><th class="px-4 py-2">Interested item</th><th class="px-4 py-2">Owner</th></tr></thead><tbody class="divide-y">@forelse($warmLeads as $lead)<tr><td class="px-4 py-3 font-semibold">{{ $lead->name }}</td><td class="px-4 py-3">{{ $lead->phone ?: '—' }}</td><td class="px-4 py-3">{{ $lead->product?->name ?: '—' }}</td><td class="px-4 py-3">{{ $lead->owner?->name ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-slate-500">No warm leads yet.</td></tr>@endforelse</tbody></table></article>
    <article class="border border-slate-200 bg-white"><div class="flex items-center justify-between border-b px-4 py-3"><h2 class="font-semibold text-rose-600">Hot Leads</h2><a href="{{ route('leads.index') }}" class="text-xs text-teal-700">See all →</a></div><table class="w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500"><tr><th class="px-4 py-2">Name</th><th class="px-4 py-2">Contact</th><th class="px-4 py-2">Interested item</th><th class="px-4 py-2">Owner</th></tr></thead><tbody class="divide-y">@forelse($hotLeads as $lead)<tr><td class="px-4 py-3 font-semibold">{{ $lead->name }}</td><td class="px-4 py-3">{{ $lead->phone ?: '—' }}</td><td class="px-4 py-3">{{ $lead->product?->name ?: '—' }}</td><td class="px-4 py-3">{{ $lead->owner?->name ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-slate-500">No hot leads yet.</td></tr>@endforelse</tbody></table></article>
</section>
<section class="grid gap-5 xl:grid-cols-2">
    <article class="border border-slate-200 bg-white p-4"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold text-teal-600">▣ Calendar</h2><span class="text-sm text-slate-500">{{ $calendarMonth }}</span></div><div class="grid grid-cols-7 border-l border-t text-center text-xs">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $weekday)<div class="border-b border-r bg-slate-50 p-2 font-bold text-slate-500">{{ $weekday }}</div>@endforeach @foreach($calendarDays as $day)<div class="min-h-20 border-b border-r p-1 text-left {{ $day->isCurrentMonth() ? 'bg-white' : 'bg-slate-50 text-slate-400' }}"><p class="text-right text-xs {{ $day->isToday() ? 'font-bold text-[#315df4]' : '' }}">{{ $day->day }}</p>@foreach($calendarTodos->get($day->toDateString(), collect())->take(2) as $todo)<p class="mt-1 truncate rounded bg-amber-100 px-1 py-0.5 text-[10px] text-amber-800" title="{{ $todo->note }}">{{ $todo->type?->name ?: 'To do' }}</p>@endforeach</div>@endforeach</div></article>
    <article class="border border-slate-200 bg-white"><div class="flex items-center justify-between border-b px-4 py-3"><h2 class="font-semibold text-slate-700">▣ Inventory</h2><a href="{{ route('products.index') }}" class="text-xs text-teal-700">See all items →</a></div><div class="max-h-80 overflow-y-auto"><table class="w-full text-left text-xs"><thead class="sticky top-0 bg-slate-50 text-slate-500"><tr><th class="px-4 py-2">Item</th><th class="px-4 py-2 text-right">On hand</th><th class="px-4 py-2 text-right">Reorder level</th><th class="px-4 py-2">Status</th></tr></thead><tbody class="divide-y">@forelse($dashboardInventory as $item)@php($quantity = (int) ($item->stock_quantity ?? 0))<tr><td class="px-4 py-3 font-semibold">{{ $item->name }}</td><td class="px-4 py-3 text-right">{{ number_format($quantity) }} {{ $item->unit }}</td><td class="px-4 py-3 text-right">{{ number_format($item->reorder_level) }}</td><td class="px-4 py-3"><span class="{{ $quantity <= $item->reorder_level ? 'text-rose-600' : 'text-emerald-600' }}">{{ $quantity <= $item->reorder_level ? 'Low stock' : 'Available' }}</span></td></tr>@empty<tr><td colspan="4" class="px-4 py-10 text-center text-slate-500">Inventory items will appear here.</td></tr>@endforelse</tbody></table></div></article>
</section>
</div></x-app-layout>
