<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
            <div><p class="text-sm font-semibold text-[#203D9F]">Pharmacy control center</p><h1 class="mt-1 text-2xl font-black text-slate-900">Good day, {{ auth()->user()->name }}</h1><p class="mt-1 text-sm text-slate-500">Here is what is happening in your medicine shop today.</p></div>
            @if(auth()->user()->hasAnyRole(['admin', 'cashier']))<a href="{{ route('purchases.create') }}" class="inline-flex items-center justify-center gap-2 rounded-md bg-[#203D9F] px-4 py-2.5 text-sm font-semibold text-white shadow hover:bg-[#19327f]"><span class="text-lg">+</span> Receive Stock</a>@endif
        </div>
    </x-slot>

    <div class="space-y-6">
        <section class="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[#203D9F] via-[#2949b8] to-[#4b3fd4] p-6 text-white shadow-lg lg:p-8">
            <div class="absolute -right-16 -top-24 h-64 w-64 rounded-full bg-white/10"></div><div class="absolute -bottom-28 right-32 h-56 w-56 rounded-full border-[36px] border-white/5"></div>
            <div class="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div class="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-semibold text-indigo-100"><span class="h-2 w-2 rounded-full bg-emerald-400"></span>Live business overview</div><h2 class="mt-5 text-2xl font-black sm:text-3xl">Welcome back, {{ auth()->user()->name }}!</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-indigo-100">Monitor sales, profit, stock health, purchases, and employees from one pharmacy workspace.</p></div><div class="rounded-xl border border-white/15 bg-white/10 px-5 py-4 backdrop-blur"><p class="text-xs font-semibold uppercase tracking-[.18em] text-indigo-200">{{ now()->format('l') }}</p><p class="mt-1 text-lg font-bold">{{ now()->format('d F Y') }}</p><p class="mt-1 text-xs capitalize text-indigo-200">{{ auth()->user()->getRoleNames()->first() }} account</p></div></div>
        </section>

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <article class="group relative overflow-hidden rounded-xl border border-blue-100 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div class="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-blue-50"></div><div class="relative flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">Today's sales</p><p class="mt-3 text-2xl font-black text-slate-900">৳{{ number_format($todaySales, 2) }}</p><p class="mt-2 text-xs text-blue-600">Revenue received today</p></div><span class="grid h-11 w-11 place-items-center rounded-xl bg-blue-100 text-xl text-blue-700">৳</span></div></article>
            <article class="group relative overflow-hidden rounded-xl border border-emerald-100 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div class="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-emerald-50"></div><div class="relative flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">Today's gross profit</p><p class="mt-3 text-2xl font-black text-emerald-700">৳{{ number_format($todayProfit, 2) }}</p><p class="mt-2 text-xs text-emerald-600">Based on batch costs</p></div><span class="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-xl text-emerald-700">↗</span></div></article>
            <article class="group relative overflow-hidden rounded-xl border border-violet-100 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div class="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-violet-50"></div><div class="relative flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">Today's purchases</p><p class="mt-3 text-2xl font-black text-violet-700">৳{{ number_format($todayPurchases, 2) }}</p><p class="mt-2 text-xs text-violet-600">Supplier stock received</p></div><span class="grid h-11 w-11 place-items-center rounded-xl bg-violet-100 text-xl text-violet-700">▧</span></div></article>
            <article class="group relative overflow-hidden rounded-xl border border-amber-100 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div class="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-amber-50"></div><div class="relative flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">Stock purchase value</p><p class="mt-3 text-2xl font-black text-amber-700">৳{{ number_format($stockValue, 2) }}</p><p class="mt-2 text-xs text-amber-600">Current available inventory</p></div><span class="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-xl text-amber-700">▦</span></div></article>
        </section>

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <a href="{{ route('products.index') }}" class="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:border-amber-300"><span class="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 font-black text-amber-600">!</span><div><p class="text-2xl font-black text-slate-900">{{ $lowStockCount }}</p><p class="text-sm text-slate-500">Low-stock medicines</p></div></a>
            <a href="{{ route('products.index') }}" class="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:border-rose-300"><span class="grid h-11 w-11 place-items-center rounded-xl bg-rose-50 font-black text-rose-600">⌛</span><div><p class="text-2xl font-black text-slate-900">{{ $expiringCount }}</p><p class="text-sm text-slate-500">Batches expiring in 90 days</p></div></a>
            <div class="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span class="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 font-black text-cyan-600">Rx</span><div><p class="text-2xl font-black text-slate-900">{{ number_format($stockPieces) }}</p><p class="text-sm text-slate-500">Available stock pieces</p></div></div>
            @if(auth()->user()->hasRole('admin'))<a href="{{ route('attendance.index') }}" class="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:border-indigo-300"><span class="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 font-black text-indigo-600">✓</span><div><p class="text-2xl font-black text-slate-900">{{ $presentToday }}<span class="text-base font-semibold text-slate-400"> / {{ $activeEmployees }}</span></p><p class="text-sm text-slate-500">Employees present today</p></div></a>@else<div class="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span class="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 font-black text-indigo-600">✓</span><div><p class="text-2xl font-black text-slate-900">{{ $activeEmployees }}</p><p class="text-sm text-slate-500">Active team members</p></div></div>@endif
        </section>

        <section class="grid gap-6 xl:grid-cols-[1.65fr_1fr]">
            <article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:p-6"><div class="flex items-start justify-between"><div><h3 class="font-bold text-slate-900">Sales performance</h3><p class="mt-1 text-sm text-slate-500">Revenue during the last seven days</p></div><div class="rounded-lg bg-blue-50 px-3 py-2 text-right"><p class="text-[10px] font-bold uppercase tracking-wide text-blue-500">7-day total</p><p class="font-black text-blue-800">৳{{ number_format($weeklySales->sum('total'), 2) }}</p></div></div><div class="mt-7 flex h-52 items-end gap-3 border-b border-slate-200 px-1 sm:gap-5">@foreach($weeklySales as $day)<div class="group flex h-full flex-1 flex-col justify-end"><div class="relative flex flex-1 items-end justify-center"><div class="absolute bottom-full mb-2 hidden rounded bg-slate-900 px-2 py-1 text-[10px] font-semibold text-white group-hover:block">৳{{ number_format($day['total'], 2) }}</div><div class="w-full max-w-12 rounded-t-md bg-gradient-to-t from-[#203D9F] to-[#5575e8] transition hover:from-indigo-700" style="height: {{ max(5, round(($day['total'] / $maxWeeklySale) * 100)) }}%"></div></div><div class="py-3 text-center"><p class="text-xs font-bold text-slate-600">{{ $day['label'] }}</p><p class="mt-0.5 hidden text-[10px] text-slate-400 sm:block">{{ $day['date'] }}</p></div></div>@endforeach</div></article>

            <article class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h3 class="font-bold text-slate-900">Quick actions</h3><p class="mt-1 text-sm text-slate-500">Open frequently used modules</p></div><div class="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-1">
                <a href="{{ route('pos.index') }}" class="flex items-center justify-between rounded-lg bg-gradient-to-r from-[#203D9F] to-[#405fd1] p-4 text-white shadow"><div><p class="font-bold">Point of Sale</p><p class="mt-1 text-xs text-indigo-100">Create a customer invoice</p></div><span class="text-xl">→</span></a>
                @if(auth()->user()->hasAnyRole(['admin', 'cashier']))<a href="{{ route('purchases.create') }}" class="flex items-center justify-between rounded-lg border border-slate-200 p-4 hover:border-blue-300 hover:bg-blue-50"><div><p class="font-bold text-slate-800">Receive purchase</p><p class="mt-1 text-xs text-slate-500">Add supplier batches to stock</p></div><span class="text-blue-600">→</span></a>@endif @if(auth()->user()->hasRole('admin'))<a href="{{ route('products.create') }}" class="flex items-center justify-between rounded-lg border border-slate-200 p-4 hover:border-blue-300 hover:bg-blue-50"><div><p class="font-bold text-slate-800">Add medicine</p><p class="mt-1 text-xs text-slate-500">Create a catalog item</p></div><span class="text-blue-600">→</span></a>@endif
                @if(auth()->user()->hasRole('admin'))<a href="{{ route('employees.create') }}" class="flex items-center justify-between rounded-lg border border-slate-200 p-4 hover:border-blue-300 hover:bg-blue-50"><div><p class="font-bold text-slate-800">Add employee</p><p class="mt-1 text-xs text-slate-500">Create login and assign role</p></div><span class="text-blue-600">→</span></a>@endif
            </div></article>
        </section>

        @if(auth()->user()->hasRole('admin'))
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
                <div class="flex flex-col gap-4 border-b border-slate-200 px-5 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div><h3 class="font-bold text-slate-900">Employee sales</h3><p class="mt-1 text-sm text-slate-500">See how much each employee sold during the selected period.</p></div>
                    <form method="GET" action="{{ route('dashboard') }}" class="flex flex-col gap-2 sm:flex-row sm:items-end">
                        <label class="text-xs font-bold uppercase tracking-wide text-slate-500">From<input type="date" name="from" value="{{ $salesFrom->toDateString() }}" class="mt-1 block w-full rounded-md border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-blue-500 focus:ring-blue-500"></label>
                        <label class="text-xs font-bold uppercase tracking-wide text-slate-500">To<input type="date" name="to" value="{{ $salesTo->toDateString() }}" class="mt-1 block w-full rounded-md border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-blue-500 focus:ring-blue-500"></label>
                        <button class="rounded-md bg-[#203D9F] px-4 py-2 text-sm font-bold text-white hover:bg-[#19327f]">Apply</button>
                    </form>
                </div>
                <div class="overflow-x-auto"><table class="w-full min-w-[790px] text-left text-sm"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Employee</th><th class="px-5 py-3">Employee code</th><th class="px-5 py-3 text-right">Invoices</th><th class="px-5 py-3 text-right">Sales</th><th class="px-5 py-3 text-right">Paid</th><th class="px-5 py-3 text-right">Returned</th><th class="px-5 py-3 text-right">Due</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($employeeSales as $employeeSale)<tr class="hover:bg-slate-50"><td class="px-5 py-3.5 font-semibold text-slate-800">{{ $employeeSale->user?->name ?: 'Unknown employee' }}</td><td class="px-5 py-3.5 text-slate-500">{{ $employeeSale->user?->employee_code ?: '—' }}</td><td class="px-5 py-3.5 text-right font-semibold text-slate-700">{{ number_format($employeeSale->invoice_count) }}</td><td class="px-5 py-3.5 text-right font-black text-[#203D9F]">৳{{ number_format($employeeSale->total_sales, 2) }}</td><td class="px-5 py-3.5 text-right text-emerald-700">৳{{ number_format($employeeSale->total_paid, 2) }}</td><td class="px-5 py-3.5 text-right text-violet-700">৳{{ number_format($employeeSale->total_change_returned, 2) }}</td><td class="px-5 py-3.5 text-right font-semibold {{ (float) $employeeSale->total_due > 0 ? 'text-amber-700' : 'text-slate-500' }}">৳{{ number_format($employeeSale->total_due, 2) }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-10 text-center text-slate-500">No employee sales found for this period.</td></tr>@endforelse</tbody></table></div>
            </section>
        @endif

        <section class="grid gap-6 xl:grid-cols-2">
            <article class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 class="font-bold text-slate-900">Stock attention</h3><p class="mt-1 text-sm text-slate-500">Medicines at or below reorder level</p></div><a href="{{ route('products.index') }}" class="text-xs font-bold text-blue-700">View stock →</a></div><div class="divide-y divide-slate-100">@forelse($lowStockProducts as $product)<div class="flex items-center justify-between gap-4 px-5 py-3.5"><div><p class="text-sm font-semibold text-slate-800">{{ $product->name }}</p><p class="mt-1 text-xs text-slate-400">Reorder at {{ number_format($product->reorder_level) }} pieces</p></div><span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{{ number_format($product->stock_quantity ?? 0) }} left</span></div>@empty<div class="px-5 py-10 text-center"><div class="mx-auto grid h-11 w-11 place-items-center rounded-full bg-emerald-50 text-emerald-600">✓</div><p class="mt-3 text-sm font-semibold text-slate-700">Stock levels look healthy</p></div>@endforelse</div></article>
            <article class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 class="font-bold text-slate-900">Expiry watch</h3><p class="mt-1 text-sm text-slate-500">Available batches expiring within 90 days</p></div><a href="{{ route('products.index') }}" class="text-xs font-bold text-blue-700">View batches →</a></div><div class="divide-y divide-slate-100">@forelse($expiringBatches as $batch)<div class="flex items-center justify-between gap-4 px-5 py-3.5"><div><p class="text-sm font-semibold text-slate-800">{{ $batch->product->name }}</p><p class="mt-1 text-xs text-slate-400">Batch {{ $batch->batch_number ?: 'not specified' }} · {{ number_format($batch->quantity_available) }} pieces</p></div><span class="rounded-full bg-rose-50 px-3 py-1 text-xs font-bold text-rose-700">{{ $batch->expires_on->format('d M Y') }}</span></div>@empty<div class="px-5 py-10 text-center"><div class="mx-auto grid h-11 w-11 place-items-center rounded-full bg-emerald-50 text-emerald-600">✓</div><p class="mt-3 text-sm font-semibold text-slate-700">No near-expiry batches</p></div>@endforelse</div></article>
        </section>

        @if(auth()->user()->hasAnyRole(['admin', 'cashier']))<section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 class="font-bold text-slate-900">Recent purchases</h3><p class="mt-1 text-sm text-slate-500">Latest supplier stock receipts</p></div><a href="{{ route('purchases.index') }}" class="text-xs font-bold text-blue-700">All purchases →</a></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Invoice</th><th class="px-5 py-3">Supplier</th><th class="px-5 py-3">Date</th><th class="px-5 py-3 text-right">Total</th><th class="px-5 py-3 text-right">Due</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($recentPurchases as $purchase)<tr class="hover:bg-slate-50"><td class="px-5 py-3.5"><a href="{{ route('purchases.show', $purchase) }}" class="font-semibold text-blue-700">{{ $purchase->invoice_number }}</a></td><td class="px-5 py-3.5 text-slate-700">{{ $purchase->supplier->name }}</td><td class="px-5 py-3.5 text-slate-500">{{ $purchase->purchased_at->format('d M Y') }}</td><td class="px-5 py-3.5 text-right font-semibold">৳{{ number_format($purchase->total, 2) }}</td><td class="px-5 py-3.5 text-right font-semibold {{ (float)$purchase->due > 0 ? 'text-amber-700' : 'text-emerald-700' }}">৳{{ number_format($purchase->due, 2) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No purchases have been recorded.</td></tr>@endforelse</tbody></table></div></section>@endif
    </div>
</x-app-layout>
