@php
    $selectedDate = \Illuminate\Support\Carbon::parse($date);
    $statuses = $employees->mapWithKeys(fn ($employee) => [$employee->id => old("employees.{$employee->id}.status", $attendance->get($employee->id)?->status ?? 'present')]);
@endphp
<x-app-layout>
    <x-slot name="header"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-xl font-bold text-slate-900">Employee Attendance</h1><p class="mt-1 text-sm text-slate-500">Record daily presence, leave, and working times.</p></div><form method="GET" class="flex items-center gap-2"><input type="date" name="date" value="{{ $date }}" max="{{ now()->toDateString() }}" class="rounded-md border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:ring-blue-500"><button class="rounded-md bg-slate-800 px-4 py-2 text-sm font-semibold text-white">View Date</button></form></div></x-slot>

    <div class="mb-5 grid gap-4 sm:grid-cols-4">
        <div class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Employees</p><p class="mt-2 text-2xl font-black text-slate-800">{{ $employees->count() }}</p></div>
        <div class="rounded-lg border border-emerald-100 bg-emerald-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-emerald-600">Present</p><p class="mt-2 text-2xl font-black text-emerald-800">{{ $attendance->where('status', 'present')->count() }}</p></div>
        <div class="rounded-lg border border-rose-100 bg-rose-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-rose-600">Absent</p><p class="mt-2 text-2xl font-black text-rose-800">{{ $attendance->where('status', 'absent')->count() }}</p></div>
        <div class="rounded-lg border border-amber-100 bg-amber-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-amber-600">Leave / Half day</p><p class="mt-2 text-2xl font-black text-amber-800">{{ $attendance->whereIn('status', ['leave', 'half_day'])->count() }}</p></div>
    </div>

    <form method="POST" action="{{ route('attendance.store') }}" x-data="{ statuses: {{ Js::from($statuses) }}, setAll(value) { Object.keys(this.statuses).forEach(id => this.statuses[id] = value) } }">
        @csrf
        <input type="hidden" name="attendance_date" value="{{ $date }}">
        <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col justify-between gap-3 bg-gradient-to-r from-[#4165dd] to-[#2947bd] px-5 py-3 text-white sm:flex-row sm:items-center"><div><p class="text-sm font-semibold">{{ $selectedDate->format('l, d F Y') }}</p></div><div class="flex gap-2 text-xs"><button type="button" @click="setAll('present')" class="rounded-md bg-white/15 px-3 py-1.5 font-semibold hover:bg-white/25">Mark all present</button><button type="button" @click="setAll('absent')" class="rounded-md bg-white/15 px-3 py-1.5 font-semibold hover:bg-white/25">Mark all absent</button></div></div>
            <div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3.5">Employee</th><th class="px-5 py-3.5">Status</th><th class="px-5 py-3.5">Check In</th><th class="px-5 py-3.5">Check Out</th><th class="px-5 py-3.5">Notes</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse($employees as $employee)@php($record = $attendance->get($employee->id))<tr class="hover:bg-slate-50"><td class="px-5 py-4"><p class="font-semibold text-slate-800">{{ $employee->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $employee->employee_code ?: 'Legacy account' }} · {{ ucfirst($employee->getRoleNames()->first() ?: $employee->role) }}</p></td><td class="px-5 py-4"><select name="employees[{{ $employee->id }}][status]" x-model="statuses[{{ $employee->id }}]" class="w-36 rounded-md border-slate-300 py-2 text-sm focus:border-blue-500 focus:ring-blue-500"><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option><option value="half_day">Half day</option></select></td><td class="px-5 py-4"><input type="time" name="employees[{{ $employee->id }}][check_in]" value="{{ old("employees.{$employee->id}.check_in", $record?->check_in ? substr($record->check_in, 0, 5) : '') }}" :disabled="!['present','half_day'].includes(statuses[{{ $employee->id }}])" class="rounded-md border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"></td><td class="px-5 py-4"><input type="time" name="employees[{{ $employee->id }}][check_out]" value="{{ old("employees.{$employee->id}.check_out", $record?->check_out ? substr($record->check_out, 0, 5) : '') }}" :disabled="!['present','half_day'].includes(statuses[{{ $employee->id }}])" class="rounded-md border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100"></td><td class="px-5 py-4"><input name="employees[{{ $employee->id }}][notes]" value="{{ old("employees.{$employee->id}.notes", $record?->notes) }}" placeholder="Optional note" class="w-full rounded-md border-slate-300 px-3 py-2 text-sm"></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">No active employees found.</td></tr>@endforelse
            </tbody></table></div>
            <div class="flex justify-between border-t border-slate-200 bg-slate-50 px-5 py-4"><a href="{{ route('attendance.index', ['date' => $selectedDate->copy()->subDay()->toDateString()]) }}" class="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700">← Previous day</a><button @disabled($employees->isEmpty()) class="rounded-md bg-gradient-to-r from-[#4165dd] to-[#4432f2] px-5 py-2.5 text-sm font-semibold text-white shadow disabled:opacity-50">Save Attendance</button></div>
        </section>
    </form>
</x-app-layout>
