@php
    $savedValues = $savedOrder?->only(['customer_type', 'customer_id', 'discount', 'paid', 'payment_method', 'note']) ?? [];
    $initialCart = collect(old('items', $savedOrder?->items ?? []))->map(function ($row) use ($catalog) {
        $product = $catalog->firstWhere('id', (int) ($row['product_id'] ?? 0));
        return $product ? ['product_id' => $product['id'], 'name' => $product['name'], 'product' => $product, 'sale_unit' => $row['sale_unit'] ?? 'piece', 'quantity' => (int) ($row['quantity'] ?? 1)] : null;
    })->filter()->values();
@endphp
<x-app-layout>
    <x-slot name="header"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-sm font-semibold text-[#203D9F]">Fast checkout</p><h1 class="mt-1 text-2xl font-black text-slate-900">{{ $savedOrder ? 'Edit '.$savedOrder->status.' order' : 'Point of Sale' }}</h1><p class="mt-1 text-sm text-slate-500">Search medicines, choose strip or single, and complete the invoice.</p></div><div class="rounded-lg bg-slate-100 px-4 py-2.5 text-sm"><span class="text-slate-500">Cashier:</span> <strong class="text-slate-800">{{ auth()->user()->name }}</strong></div></div></x-slot>

    @if($errors->any())<div class="mb-5 rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><p class="font-bold">The sale could not be completed:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div x-data="{
        catalog: {{ Js::from($catalog) }}, catalogMeta: { current_page: 1, last_page: 1, per_page: 30, total: 0 }, catalogLoading: false, searchTimer: null, catalogUrl: {{ Js::from(route('pos.catalog')) }},
        customers: {{ Js::from($customers) }}, customerType: {{ Js::from(old('customer_type', $savedValues['customer_type'] ?? 'walking')) }}, customerId: {{ Js::from(old('customer_id', $savedValues['customer_id'] ?? '')) }},
        search: '', cart: {{ Js::from($initialCart) }}, discount: {{ Js::from((float) old('discount', $savedValues['discount'] ?? 0)) }}, paid: {{ Js::from((float) old('paid', $savedValues['paid'] ?? 0)) }}, paymentMethod: {{ Js::from(old('payment_method', $savedValues['payment_method'] ?? 'cash')) }},
        filteredCustomers() { return this.customers.filter(customer => customer.customer_type === this.customerType) },
        selectedCustomer() { return this.customers.find(customer => String(customer.id) === String(this.customerId)) },
        init() { this.fetchCatalog() },
        searchChanged() { clearTimeout(this.searchTimer); this.searchTimer = setTimeout(() => this.fetchCatalog(1), 250) },
        async fetchCatalog(page = 1) { this.catalogLoading = true; try { const url = new URL(this.catalogUrl, window.location.origin); url.searchParams.set('page', page); if (this.search.trim()) url.searchParams.set('search', this.search.trim()); const response = await fetch(url, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('Catalog request failed'); const payload = await response.json(); this.catalog = payload.data; this.catalogMeta = payload.meta; } catch (error) { this.catalog = []; this.catalogMeta = { current_page: 1, last_page: 1, per_page: 30, total: 0 }; } finally { this.catalogLoading = false; } },
        maxUnits(product, unit) { return unit === 'strip' ? product.strip_stock : product.piece_stock },
        displayPrice(product, unit) { return Number(unit === 'strip' ? product.strip_price : product.piece_price) || 0 },
        add(product, unit) { const max = this.maxUnits(product, unit); if (max < 1) return; const existing = this.cart.find(item => item.product_id === product.id); if (existing) { if (existing.sale_unit !== unit) { existing.sale_unit = unit; existing.quantity = 1 } else if (existing.quantity < max) existing.quantity++ } else this.cart.push({ product_id: product.id, name: product.name, product, sale_unit: unit, quantity: 1 }) },
        remove(index) { this.cart.splice(index, 1) },
        clamp(item) { item.quantity = Math.max(1, Math.min(Number(item.quantity) || 1, this.maxUnits(item.product, item.sale_unit))) },
        lineTotal(item) { let remaining = Number(item.quantity) || 0, total = 0; const multiplier = item.sale_unit === 'strip' ? item.product.pieces_per_strip : 1; for (const batch of item.product.batches) { const price = item.sale_unit === 'strip' ? batch.strip_price : batch.piece_price; if (price === null) continue; const available = Math.floor(batch.quantity / multiplier); const take = Math.min(remaining, available); total += take * Number(price); remaining -= take; if (remaining <= 0) break } return total },
        get subtotal() { return this.cart.reduce((sum, item) => sum + this.lineTotal(item), 0) },
        get total() { return Math.max(0, this.subtotal - (Number(this.discount) || 0)) },
        get change() { return Math.max(0, (Number(this.paid) || 0) - this.total) },
        get due() { return Math.max(0, this.total - (Number(this.paid) || 0)) },
        exactPayment() { this.paid = Number(this.total.toFixed(2)) },
        money(value) { return Number(value || 0).toFixed(2) }
    }" class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_430px]">
        <section class="min-w-0">
            <div class="sticky top-0 z-10 mb-5 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="relative"><svg class="absolute left-4 top-3.5 h-5 w-5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21-4.35-4.35m2.35-5.65a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z"/></svg><input x-model="search" @input="searchChanged()" autofocus placeholder="Search Napa, Paracetamol, Tablet, Square or barcode..." class="block w-full rounded-lg border-slate-300 py-3 pl-12 pr-4 text-sm focus:border-blue-500 focus:ring-blue-500"></div><div class="mt-3 flex items-center justify-between text-xs text-slate-500"><span x-show="!catalogLoading"><strong x-text="catalogMeta.total"></strong> medicines found · showing <strong x-text="catalog.length"></strong></span><span x-show="catalogLoading" class="font-semibold text-blue-700">Searching medicines…</span><button type="button" x-show="search" @click="search = ''; fetchCatalog(1)" class="font-semibold text-blue-700">Clear search</button></div></div>

            <div class="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">
                <template x-for="product in catalog" :key="product.id"><article class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div class="flex gap-4 p-4"><div class="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-blue-50 to-indigo-100 font-black text-[#203D9F]">Rx</div><div class="min-w-0"><h3 class="truncate font-bold text-slate-900" x-text="product.name"></h3><p class="mt-1 truncate text-xs text-slate-500" x-text="[product.generic, product.category ? product.category.charAt(0).toUpperCase() + product.category.slice(1) : null, product.supplier].filter(Boolean).join(' · ') || 'Medicine'"></p><p x-show="product.barcode" class="mt-1 truncate font-mono text-[10px] text-slate-400">Barcode: <span x-text="product.barcode"></span></p><p class="mt-2 text-xs font-semibold text-emerald-700"><span x-text="product.piece_stock"></span> pieces in stock</p></div></div><div class="grid grid-cols-2 border-t border-slate-100 bg-slate-50">
                    <button type="button" @click="add(product, 'piece')" :disabled="!product.sell_by_piece || product.piece_stock < 1" class="border-r border-slate-200 px-3 py-3 text-left hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-35"><span class="block text-[10px] font-bold uppercase tracking-wide text-slate-400">Single</span><span class="mt-1 block text-sm font-black text-blue-700">৳<span x-text="money(product.piece_price)"></span></span></button>
                    <button type="button" @click="add(product, 'strip')" :disabled="!product.sell_by_strip || product.strip_stock < 1 || product.strip_price === null" class="px-3 py-3 text-left hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-35"><span class="block text-[10px] font-bold uppercase tracking-wide text-slate-400">Strip · <span x-text="product.pieces_per_strip"></span> pcs</span><span class="mt-1 block text-sm font-black text-indigo-700">৳<span x-text="money(product.strip_price)"></span></span></button>
                </div></article></template>
            </div>
            <div x-show="!catalogLoading && catalog.length === 0" x-cloak class="rounded-xl border border-dashed border-slate-300 bg-white py-16 text-center"><div class="mx-auto grid h-14 w-14 place-items-center rounded-full bg-slate-100 text-xl">Rx</div><p class="mt-4 font-bold text-slate-700">No medicine found</p><p class="mt-1 text-sm text-slate-500">Try another name, generic, supplier, category, or barcode.</p></div>
            <div x-show="catalogMeta.last_page > 1" x-cloak class="mt-5 flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm shadow-sm"><button type="button" @click="fetchCatalog(catalogMeta.current_page - 1)" :disabled="catalogMeta.current_page <= 1 || catalogLoading" class="rounded-md border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 disabled:cursor-not-allowed disabled:opacity-40">← Previous</button><span class="text-slate-500">Page <strong class="text-slate-800" x-text="catalogMeta.current_page"></strong> of <strong class="text-slate-800" x-text="catalogMeta.last_page"></strong></span><button type="button" @click="fetchCatalog(catalogMeta.current_page + 1)" :disabled="catalogMeta.current_page >= catalogMeta.last_page || catalogLoading" class="rounded-md border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 disabled:cursor-not-allowed disabled:opacity-40">Next →</button></div>
        </section>

        <form method="POST" action="{{ route('pos.store') }}" class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-lg xl:sticky xl:top-5">
            @csrf
            @if($savedOrder)<input type="hidden" name="saved_order_id" value="{{ $savedOrder->id }}">@endif
            <div class="flex items-center justify-between bg-[#203D9F] px-5 py-4 text-white"><div><h2 class="font-bold">Current Sale</h2><p class="mt-0.5 text-xs text-blue-200"><span x-text="cart.length"></span> medicine(s)</p></div><button type="button" @click="cart = []; discount = 0; paid = 0" x-show="cart.length" class="rounded-md bg-white/10 px-3 py-1.5 text-xs font-semibold hover:bg-white/20">Clear</button></div>
            <div class="border-b border-slate-200 bg-blue-50/60 p-4"><label class="text-[10px] font-bold uppercase tracking-wide text-slate-500">Customer type</label><div class="mt-2 grid grid-cols-3 gap-2"><label class="cursor-pointer"><input type="radio" name="customer_type" value="walking" x-model="customerType" @change="customerId = ''" class="peer sr-only"><span class="block rounded-md border border-slate-200 bg-white px-2 py-2 text-center text-xs font-semibold text-slate-600 peer-checked:border-blue-500 peer-checked:bg-blue-600 peer-checked:text-white">Walking</span></label><label class="cursor-pointer"><input type="radio" name="customer_type" value="retail" x-model="customerType" @change="customerId = ''" class="peer sr-only"><span class="block rounded-md border border-slate-200 bg-white px-2 py-2 text-center text-xs font-semibold text-slate-600 peer-checked:border-blue-500 peer-checked:bg-blue-600 peer-checked:text-white">Retail</span></label><label class="cursor-pointer"><input type="radio" name="customer_type" value="wholesale" x-model="customerType" @change="customerId = ''" class="peer sr-only"><span class="block rounded-md border border-slate-200 bg-white px-2 py-2 text-center text-xs font-semibold text-slate-600 peer-checked:border-violet-500 peer-checked:bg-violet-600 peer-checked:text-white">Wholesale</span></label></div><div x-show="customerType !== 'walking'" x-cloak class="mt-3"><select name="customer_id" x-model="customerId" :required="customerType !== 'walking'" class="block w-full rounded-md border-slate-300 py-2 text-sm"><option value="">Select saved customer</option><template x-for="customer in filteredCustomers()" :key="customer.id"><option :value="customer.id" x-text="`${customer.name} · ${customer.phone}`"></option></template></select><div x-show="selectedCustomer()" class="mt-2 flex justify-between rounded-md bg-white px-3 py-2 text-xs"><span class="text-slate-500">Previous due</span><strong class="text-amber-700">৳<span x-text="money(selectedCustomer()?.due_balance)"></span></strong></div></div><div x-show="customerType === 'walking'" class="mt-3 rounded-md bg-white px-3 py-2 text-xs text-slate-500">No saved customer is required. Full payment is mandatory.</div></div>
            <div class="max-h-[390px] min-h-[180px] overflow-y-auto"><div x-show="cart.length === 0" class="px-6 py-14 text-center"><div class="mx-auto grid h-14 w-14 place-items-center rounded-full bg-slate-100 text-xl text-slate-400">▣</div><p class="mt-4 font-bold text-slate-700">Cart is empty</p><p class="mt-1 text-sm text-slate-400">Click Single or Strip on a medicine.</p></div><div class="divide-y divide-slate-100"><template x-for="(item, index) in cart" :key="item.product_id"><div class="p-4"><input type="hidden" :name="`items[${index}][product_id]`" :value="item.product_id"><input type="hidden" :name="`items[${index}][sale_unit]`" :value="item.sale_unit"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-bold text-slate-800" x-text="item.name"></p><div class="mt-1 flex items-center gap-2"><span class="rounded bg-indigo-50 px-2 py-0.5 text-[10px] font-bold uppercase text-indigo-700" x-text="item.sale_unit"></span><span class="text-xs text-slate-400">৳<span x-text="money(displayPrice(item.product, item.sale_unit))"></span> starting price</span></div></div><button type="button" @click="remove(index)" class="grid h-7 w-7 place-items-center rounded-full bg-rose-50 text-sm font-bold text-rose-600 hover:bg-rose-100">×</button></div><div class="mt-3 flex items-center justify-between"><div class="flex items-center rounded-md border border-slate-300"><button type="button" @click="item.quantity > 1 && item.quantity--;" class="h-8 w-8 font-bold text-slate-600">−</button><input type="number" min="1" :max="maxUnits(item.product, item.sale_unit)" :name="`items[${index}][quantity]`" x-model.number="item.quantity" @change="clamp(item)" class="h-8 w-12 border-0 p-0 text-center text-sm font-bold focus:ring-0"><button type="button" @click="item.quantity < maxUnits(item.product, item.sale_unit) && item.quantity++;" class="h-8 w-8 font-bold text-slate-600">+</button></div><p class="font-black text-slate-900">৳<span x-text="money(lineTotal(item))"></span></p></div></div></template></div></div>
            <div class="border-t border-slate-200 bg-slate-50 p-5"><div class="space-y-3 text-sm"><div class="flex justify-between text-slate-600"><span>Subtotal</span><strong class="text-slate-900">৳<span x-text="money(subtotal)"></span></strong></div><label class="flex items-center justify-between text-slate-600"><span>Discount</span><input type="number" name="discount" min="0" step="0.01" x-model.number="discount" class="w-28 rounded-md border-slate-300 px-3 py-1.5 text-right text-sm"></label><div class="flex justify-between border-t border-slate-200 pt-3 text-lg"><span class="font-black text-slate-900">Total</span><strong class="text-[#203D9F]">৳<span x-text="money(total)"></span></strong></div></div>
                <div class="mt-4 grid grid-cols-2 gap-3"><div><label class="text-xs font-bold uppercase tracking-wide text-slate-500">Payment</label><select name="payment_method" x-model="paymentMethod" class="mt-1.5 block w-full rounded-md border-slate-300 py-2 text-sm"><option value="cash">Cash</option><option value="card">Card</option><option value="mobile_banking">Mobile banking</option></select></div><div><div class="flex items-center justify-between"><label class="text-xs font-bold uppercase tracking-wide text-slate-500">Received</label><button type="button" @click="exactPayment()" class="text-[10px] font-bold text-blue-700">Exact</button></div><input type="number" name="paid" min="0" step="0.01" x-model.number="paid" class="mt-1.5 block w-full rounded-md border-slate-300 px-3 py-2 text-right text-sm"></div></div>
                <div x-show="due > 0 && customerType !== 'walking'" class="mt-4 flex items-center justify-between rounded-lg bg-amber-50 px-3 py-2.5"><span class="text-sm font-semibold text-amber-800">New customer due</span><strong class="text-amber-800">৳<span x-text="money(due)"></span></strong></div><div x-show="due === 0" class="mt-4 flex items-center justify-between rounded-lg bg-emerald-50 px-3 py-2.5"><span class="text-sm font-semibold text-emerald-800">Change</span><strong class="text-emerald-800">৳<span x-text="money(change)"></span></strong></div>
                <div class="mt-4"><label class="text-xs font-bold uppercase tracking-wide text-slate-500">Order note <span class="normal-case font-medium">optional</span></label><input name="note" value="{{ old('note', $savedValues['note'] ?? '') }}" placeholder="Customer request or quick reminder" class="mt-1.5 block w-full rounded-md border-slate-300 px-3 py-2 text-sm"></div>
                <div class="mt-4 grid grid-cols-2 gap-2"><button type="submit" formaction="{{ route('pos.saved-orders.store') }}" name="status" value="held" :disabled="cart.length === 0" class="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2.5 text-sm font-bold text-amber-800 hover:bg-amber-100 disabled:opacity-40">Hold Order</button><button type="submit" formaction="{{ route('pos.saved-orders.store') }}" name="status" value="draft" :disabled="cart.length === 0" class="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-40">Save Draft</button></div>
                <button :disabled="cart.length === 0 || (customerType === 'walking' && Number(paid) < total) || (customerType !== 'walking' && !customerId)" class="mt-2 w-full rounded-lg bg-gradient-to-r from-[#203D9F] to-[#405fd1] px-5 py-3 text-sm font-bold text-white shadow hover:opacity-95 disabled:cursor-not-allowed disabled:opacity-40">Complete Sale & View Invoice</button>
            </div>
        </form>

        @if($recentSales->isNotEmpty())<section class="xl:col-start-2"><div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 class="text-sm font-bold text-slate-800">Your recent sales</h3><div class="mt-3 space-y-2">@foreach($recentSales as $sale)<a href="{{ route('sales.show', $sale) }}" class="flex items-center justify-between rounded-md bg-slate-50 px-3 py-2 text-xs hover:bg-blue-50"><span class="font-semibold text-blue-700">{{ $sale->invoice_number }}</span><span class="font-bold text-slate-700">৳{{ number_format($sale->total, 2) }}</span></a>@endforeach</div></div></section>@endif
    </div>
</x-app-layout>
