@csrf
@if(isset($supplier)) @method('PUT') @endif
<div class="grid max-w-5xl gap-5 md:grid-cols-2">
    <div><label class="text-sm font-semibold text-slate-700">Supplier name <span class="text-rose-500">*</span></label><input name="name" value="{{ old('name',$supplier->name ?? '') }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('name')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Phone</label><input name="phone" value="{{ old('phone',$supplier->phone ?? '') }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('phone')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Email</label><input type="email" name="email" value="{{ old('email',$supplier->email ?? '') }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('email')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Address</label><textarea name="address" rows="3" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500">{{ old('address',$supplier->address ?? '') }}</textarea><x-input-error :messages="$errors->get('address')" class="mt-2"/></div>
</div>
<label class="mt-5 flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$supplier->is_active ?? true)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500">Active</label>
<div class="mt-7 flex gap-3 border-t border-slate-100 pt-5"><button class="rounded-md bg-[#3656d8] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#2946be]">{{ isset($supplier) ? 'Update Supplier' : 'Save Supplier' }}</button><a href="{{ route('suppliers.index') }}" class="rounded-md border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</a></div>
