<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><h1 class="text-xl font-bold text-slate-900">Sales Collection</h1><a href="{{ route('sales-collections.create') }}" class="rounded bg-[#1f7d88] px-4 py-2 text-sm font-semibold text-white">Add New</a></div></x-slot>
    <section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <form class="mb-4 grid gap-3 md:grid-cols-2 lg:grid-cols-5">
            <select name="segment" class="rounded border-slate-300 text-sm"><option value="">[Select Segment]</option>@foreach($segments as $segment)<option value="{{ $segment->id }}" @selected(($filters['segment']??'') == $segment->id)>{{ $segment->name }}</option>@endforeach</select>
            <input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="rounded border-slate-300 text-sm"><input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="rounded border-slate-300 text-sm">
            <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Inv No/Customer/Phone/Dealer" class="rounded border-slate-300 text-sm"><button class="rounded bg-[#1f7d88] px-4 py-2 text-sm font-semibold text-white">Search</button>
        </form>
        <div class="mb-4 flex items-center justify-between"><p class="text-sm font-bold">Total Collection Amount: ৳{{ number_format($collections->sum('amount'), 2) }}</p><button onclick="window.print()" class="rounded bg-slate-100 px-3 py-2 text-sm">Export / Print</button></div>
        <div class="overflow-x-auto"><table class="js-data-table w-full min-w-[1050px] text-left text-sm"><thead><tr><th>SL.</th><th>Collection Date</th><th>Invoice No &amp; Date</th><th>Customer</th><th>Dealer</th><th>Paid Amount</th><th>Mode of Payment</th><th>Remarks</th></tr></thead><tbody>@foreach($collections as $collection)<tr><td>{{ $loop->iteration }}</td><td>{{ \Carbon\Carbon::parse($collection->received_at)->format('d-m-y') }}</td><td>{{ $collection->sale_no ?? '—' }}<br><span class="text-xs text-slate-500">{{ $collection->sale_date ? \Carbon\Carbon::parse($collection->sale_date)->format('d-m-y') : '' }}</span></td><td>{{ $collection->customer_name ?? '—' }}<br><span class="text-xs text-slate-500">{{ $collection->customer_phone }}</span></td><td>{{ $collection->dealer ?: 'Self' }}</td><td class="font-semibold">৳{{ number_format($collection->amount, 2) }}</td><td>{{ ucfirst(str_replace('_', ' ', $collection->payment_mode)) }}</td><td>{{ $collection->remarks ?: '—' }}</td></tr>@endforeach</tbody></table></div>
    </section>
</x-app-layout>
