<x-app-layout>
    <x-slot name="header"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-xl font-bold text-slate-900">Purchases</h1><p class="mt-1 text-sm text-slate-500">Receive supplier invoices and automatically increase batch stock.</p></div><a href="{{ route('purchases.create') }}" class="inline-flex items-center justify-center gap-2 rounded-md bg-gradient-to-r from-[#4165dd] to-[#4432f2] px-4 py-2.5 text-sm font-semibold text-white shadow">+ New Purchase</a></div></x-slot>

    <form class="mb-5 flex max-w-xl gap-2"><input name="search" value="{{ $search }}" placeholder="Search invoice or supplier" class="block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><button class="rounded-md bg-slate-800 px-5 py-2.5 text-sm font-semibold text-white">Search</button>@if($search)<a href="{{ route('purchases.index') }}" class="rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">Clear</a>@endif</form>

    <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
        <div class="bg-gradient-to-r from-[#4165dd] to-[#2947bd] px-5 py-3 text-sm font-semibold text-white">Purchase History</div>
        <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3.5">Invoice</th><th class="px-5 py-3.5">Supplier</th><th class="px-5 py-3.5">Date</th><th class="px-5 py-3.5 text-center">Items</th><th class="px-5 py-3.5 text-right">Total</th><th class="px-5 py-3.5">Payment</th><th class="px-5 py-3.5 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($purchases as $purchase)<tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-blue-700">{{ $purchase->invoice_number }}</td><td class="px-5 py-4"><p class="font-semibold text-slate-800">{{ $purchase->supplier->name }}</p><p class="mt-1 text-xs text-slate-400">Received by {{ $purchase->user->name }}</p></td><td class="px-5 py-4 text-slate-600">{{ $purchase->purchased_at->format('d M Y') }}</td><td class="px-5 py-4 text-center font-semibold">{{ $purchase->items_count }}</td><td class="px-5 py-4 text-right font-bold text-slate-800">৳{{ number_format($purchase->total, 2) }}</td><td class="px-5 py-4">@if((float)$purchase->paid >= (float)$purchase->total)<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Paid</span>@elseif((float)$purchase->paid > 0)<span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">Partial</span>@else<span class="rounded-full bg-rose-50 px-2.5 py-1 text-xs font-semibold text-rose-700">Due</span>@endif</td><td class="px-5 py-4 text-right"><a href="{{ route('purchases.show', $purchase) }}" class="inline-flex items-center rounded-md border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700 hover:bg-blue-100">View Invoice</a></td></tr>
            @empty<tr><td colspan="7" class="px-5 py-14 text-center text-slate-500">No purchases recorded yet.</td></tr>@endforelse
        </tbody></table></div><div class="border-t border-slate-200 px-5 py-4">{{ $purchases->links() }}</div>
    </section>
</x-app-layout>
