<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><h1 class="text-xl font-bold text-slate-900">Add Lead</h1><p class="mt-1 text-sm text-slate-500">Create a new relationship opportunity and assign its owner.</p></div><a href="{{ route('leads.index') }}" class="text-sm font-semibold text-indigo-700">← Leads list</a></div></x-slot>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="bg-gradient-to-r from-[#4165dd] to-[#2947bd] px-6 py-4 text-sm font-semibold text-white">GENERAL INFO</div><form method="POST" action="{{ route('leads.store') }}" enctype="multipart/form-data" class="p-6 sm:p-8">@csrf
        <div class="grid gap-x-7 gap-y-5 md:grid-cols-2 xl:grid-cols-4">
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Lead name<input name="name" value="{{ old('name') }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm" required>@error('name')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Contact no. 1<input name="phone" value="{{ old('phone') }}" placeholder="01XXXXXXXXX" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></label>
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Contact no. 2<input name="alternate_phone" value="{{ old('alternate_phone') }}" placeholder="01XXXXXXXXX" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></label>
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Email<input name="email" type="email" value="{{ old('email') }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></label>
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Organization<select name="organization_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select organization</option>@foreach($lookups['organizations'] as $item)<option value="{{ $item->id }}" @selected(old('organization_id') == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Address<input name="address" value="{{ old('address') }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></label>
            <label class="block text-sm font-semibold text-slate-700">Job position / profession<input name="job_title" value="{{ old('job_title') }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></label>
            <label class="block text-sm font-semibold text-slate-700">Segment<select name="segment_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select segment</option>@foreach($lookups['segments'] as $item)<option value="{{ $item->id }}" @selected(old('segment_id') == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Product<select name="product_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select product</option>@foreach($lookups['products'] as $item)<option value="{{ $item->id }}" @selected(old('product_id') == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Color<select name="color_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select color</option>@foreach($lookups['colors'] as $item)<option value="{{ $item->id }}" @selected(old('color_id') == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Lead status<select name="lead_status_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm" required>@foreach($lookups['statuses'] as $item)<option value="{{ $item->id }}" @selected(old('lead_status_id') == $item->id || (!old('lead_status_id') && strtolower($item->name) === 'cold'))>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Lead pipeline<select name="pipeline_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select pipeline</option>@foreach($lookups['pipelines'] as $item)<option value="{{ $item->id }}" @selected(old('pipeline_id') == $item->id)>{{ $item->code ? $item->code.' · ' : '' }}{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Activity type<select name="activity_type_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select type</option>@foreach($lookups['activityTypes'] as $item)<option value="{{ $item->id }}" @selected(old('activity_type_id') == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Owner / assigned to<select name="owner_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm" required>@foreach($lookups['users'] as $item)<option value="{{ $item->id }}" @selected(old('owner_id', auth()->id()) == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Lead date<input name="lead_date" type="date" value="{{ old('lead_date', today()->format('Y-m-d')) }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm" required></label>
            <label class="block text-sm font-semibold text-slate-700">Business card<input name="business_card" type="file" accept="image/*" class="mt-2 block w-full text-sm text-slate-500 file:mr-3 file:rounded-md file:border-0 file:bg-indigo-50 file:px-3 file:py-2 file:font-semibold file:text-indigo-700"></label>
            <label class="block text-sm font-semibold text-slate-700">Source<select name="source_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select source</option>@foreach($lookups['sources'] as $item)<option value="{{ $item->id }}" @selected(old('source_id') == $item->id)>{{ $item->name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700">Source details<input name="source_detail" value="{{ old('source_detail') }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></label>
            <label class="block text-sm font-semibold text-slate-700 xl:col-span-2">Remarks<textarea name="remarks" rows="3" class="mt-2 block w-full rounded-md border-slate-300 text-sm">{{ old('remarks') }}</textarea></label>
        </div><div class="mt-7 flex gap-3 border-t border-slate-100 pt-6"><button class="rounded-md bg-[#1f7d88] px-5 py-2.5 text-sm font-semibold text-white">Save lead</button><a href="{{ route('leads.index') }}" class="rounded-md bg-slate-100 px-5 py-2.5 text-sm font-semibold text-slate-700">Cancel</a></div>
    </form></section>
</x-app-layout>
