<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><div><h1 class="text-xl font-bold text-slate-900">Bulk SMS Blast</h1><p class="mt-1 text-sm text-slate-500">Create a message, choose an audience, then queue it for delivery.</p></div><a href="{{ route('bulk-sms.index') }}" class="text-sm font-semibold text-indigo-700">SMS send list →</a></div></x-slot>
    <form method="POST" action="{{ route('bulk-sms.store') }}" x-data="smsBlast()" class="grid gap-6 xl:grid-cols-[1fr_380px]">@csrf
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 class="font-bold text-slate-800">Recipients</h2>
            <div class="mt-4 grid gap-3 sm:grid-cols-2">
                <label class="rounded-lg border p-4" :class="audience === 'both' ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200'"><input type="radio" name="audience" value="both" x-model="audience" class="sr-only"><span class="font-semibold text-slate-800">All contacts and leads</span><span class="mt-1 block text-xs text-slate-500">Send to every saved CRM mobile number.</span></label>
                <label class="rounded-lg border p-4" :class="audience === 'contacts' ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200'"><input type="radio" name="audience" value="contacts" x-model="audience" class="sr-only"><span class="font-semibold text-slate-800">Contacts only</span><span class="mt-1 block text-xs text-slate-500">{{ $contacts->count() }} available contacts.</span></label>
                <label class="rounded-lg border p-4" :class="audience === 'leads' ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200'"><input type="radio" name="audience" value="leads" x-model="audience" class="sr-only"><span class="font-semibold text-slate-800">Leads only</span><span class="mt-1 block text-xs text-slate-500">{{ $leads->count() }} available leads.</span></label>
                <label class="rounded-lg border p-4" :class="audience === 'manual' ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200'"><input type="radio" name="audience" value="manual" x-model="audience" class="sr-only"><span class="font-semibold text-slate-800">Paste phone numbers</span><span class="mt-1 block text-xs text-slate-500">One number per line, comma, or space.</span></label>
            </div>
            <div x-show="audience !== 'manual'" class="mt-6 rounded-lg bg-slate-50 p-4">
                <div class="flex flex-wrap items-center justify-between gap-3"><p class="text-sm font-semibold text-slate-700">Recipient selection</p><div class="flex gap-2"><label class="text-sm"><input type="radio" name="selection_mode" value="all" x-model="selectionMode"> All matching</label><label class="text-sm"><input type="radio" name="selection_mode" value="selected" x-model="selectionMode"> Choose recipients</label></div></div>
                <div x-show="selectionMode === 'selected'" class="mt-4 grid gap-4 md:grid-cols-2">
                    <template x-if="audience === 'contacts' || audience === 'both'"><label class="block text-sm font-semibold text-slate-700">Contacts<select name="contact_ids[]" multiple class="mt-2 h-40 w-full rounded-md border-slate-300 text-sm">@foreach($contacts as $contact)<option value="{{ $contact->id }}">{{ $contact->name }} — {{ $contact->mobile_1 }}</option>@endforeach</select><span class="mt-1 block text-xs font-normal text-slate-500">Use Ctrl/Cmd to select multiple.</span></label></template>
                    <template x-if="audience === 'leads' || audience === 'both'"><label class="block text-sm font-semibold text-slate-700">Leads<select name="lead_ids[]" multiple class="mt-2 h-40 w-full rounded-md border-slate-300 text-sm">@foreach($leads as $lead)<option value="{{ $lead->id }}">{{ $lead->name }} — {{ $lead->phone }}</option>@endforeach</select><span class="mt-1 block text-xs font-normal text-slate-500">Use Ctrl/Cmd to select multiple.</span></label></template>
                </div>
            </div>
            <label x-show="audience === 'manual'" class="mt-6 block text-sm font-semibold text-slate-700">Phone numbers<textarea name="manual_phones" rows="6" placeholder="017XXXXXXXX&#10;018XXXXXXXX" class="mt-2 block w-full rounded-md border-slate-300 text-sm"></textarea></label>
        </section>
        <aside class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-bold text-slate-800">Message</h2><label class="mt-4 block text-sm font-semibold text-slate-700">SMS text<textarea name="message" x-model="message" maxlength="1000" rows="9" placeholder="Write your promotion or reminder…" class="mt-2 block w-full rounded-md border-slate-300 text-sm" required>{{ old('message') }}</textarea><span class="mt-1 block text-xs text-slate-500"><span x-text="message.length"></span>/1000 characters</span></label>@error('recipients')<p class="mt-3 text-sm text-rose-600">{{ $message }}</p>@enderror<div class="mt-6 border-t border-slate-100 pt-5"><button class="w-full rounded-md bg-[#1f7d88] px-5 py-3 text-sm font-semibold text-white hover:bg-[#176973]">Queue SMS blast</button><a href="{{ route('bulk-sms.index') }}" class="mt-3 block text-center text-sm font-semibold text-rose-700">Cancel</a></div></aside>
    </form>
    <script>function smsBlast(){return {audience:'{{ old('audience', 'both') }}',selectionMode:'{{ old('selection_mode', 'all') }}',message:@json(old('message', ''))}}</script>
</x-app-layout>
