<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-[#203D9F]">Business intelligence</p><h1 class="mt-1 text-2xl font-black text-slate-900">Pharmacy Reports</h1><p class="mt-1 text-sm text-slate-500">Review purchases, sales, inventory value, and replenishment needs.</p></div></x-slot>
    @include('admin.reports._tabs')
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-xl border border-violet-100 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">Purchases this month</p><p class="mt-3 text-2xl font-black text-violet-700">৳{{ number_format($monthlyPurchases, 2) }}</p></div>
        <div class="rounded-xl border border-blue-100 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">Sales this month</p><p class="mt-3 text-2xl font-black text-blue-700">৳{{ number_format($monthlySales, 2) }}</p></div>
        <div class="rounded-xl border border-emerald-100 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">Current stock value</p><p class="mt-3 text-2xl font-black text-emerald-700">৳{{ number_format($stockValue, 2) }}</p></div>
        <div class="rounded-xl border border-amber-100 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">Products needing stock</p><p class="mt-3 text-2xl font-black text-amber-700">{{ number_format($neededProducts) }}</p></div>
    </section>
    <section class="mt-6 grid gap-5 md:grid-cols-2">
        <a href="{{ route('reports.purchases') }}" class="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md"><div class="flex items-center gap-4 p-6"><span class="grid h-14 w-14 place-items-center rounded-xl bg-violet-50 text-2xl text-violet-700">▧</span><div><h2 class="text-lg font-black text-slate-900">Purchase Report</h2><p class="mt-1 text-sm text-slate-500">Supplier invoices, payments, discounts, and outstanding dues.</p></div><span class="ml-auto text-xl text-violet-600">→</span></div></a>
        <a href="{{ route('reports.sales') }}" class="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div class="flex items-center gap-4 p-6"><span class="grid h-14 w-14 place-items-center rounded-xl bg-blue-50 text-2xl text-blue-700">৳</span><div><h2 class="text-lg font-black text-slate-900">Sales Report</h2><p class="mt-1 text-sm text-slate-500">Employee sales, revenue, discounts, and gross profit.</p></div><span class="ml-auto text-xl text-blue-600">→</span></div></a>
        <a href="{{ route('reports.product-supplier-sales') }}" class="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-300 hover:shadow-md"><div class="flex items-center gap-4 p-6"><span class="grid h-14 w-14 place-items-center rounded-xl bg-indigo-50 text-2xl text-indigo-700">≋</span><div><h2 class="text-lg font-black text-slate-900">Product &amp; Supplier Sales</h2><p class="mt-1 text-sm text-slate-500">Sales, cost, and profit by medicine and supplying company.</p></div><span class="ml-auto text-xl text-indigo-600">→</span></div></a>
        <a href="{{ route('reports.stock') }}" class="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div class="flex items-center gap-4 p-6"><span class="grid h-14 w-14 place-items-center rounded-xl bg-emerald-50 text-2xl text-emerald-700">▦</span><div><h2 class="text-lg font-black text-slate-900">Stock Report</h2><p class="mt-1 text-sm text-slate-500">Available pieces, strips, batches, and inventory valuation.</p></div><span class="ml-auto text-xl text-emerald-600">→</span></div></a>
        <a href="{{ route('reports.needed') }}" class="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-amber-300 hover:shadow-md"><div class="flex items-center gap-4 p-6"><span class="grid h-14 w-14 place-items-center rounded-xl bg-amber-50 text-2xl font-black text-amber-700">!</span><div><h2 class="text-lg font-black text-slate-900">Product Needed Report</h2><p class="mt-1 text-sm text-slate-500">Low and out-of-stock products with suggested order quantities.</p></div><span class="ml-auto text-xl text-amber-600">→</span></div></a>
    </section>
</x-app-layout>
