<x-app-layout>
    <x-slot name="header"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-2xl font-black text-slate-900">Product &amp; Supplier Sales</h1><p class="mt-1 text-sm text-slate-500">Track sales from each medicine batch and its supplier.</p></div><button onclick="window.print()" class="rounded-md bg-[#203D9F] px-4 py-2.5 text-sm font-semibold text-white print:hidden">Print Report</button></div></x-slot>

    @include('admin.reports._tabs')

    <div class="mb-5 hidden print:block"><h1 class="text-2xl font-black">Product &amp; Supplier Sales</h1><p class="mt-1 text-sm">{{ $from->format('d M Y') }} – {{ $to->format('d M Y') }}</p></div>

    <form method="GET" class="mb-6 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm print:hidden md:grid-cols-4"><div><label class="text-xs font-bold uppercase tracking-wide text-slate-500">From</label><input type="date" name="from" value="{{ $from->toDateString() }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2 text-sm"></div><div><label class="text-xs font-bold uppercase tracking-wide text-slate-500">To</label><input type="date" name="to" value="{{ $to->toDateString() }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2 text-sm"></div><div><label class="text-xs font-bold uppercase tracking-wide text-slate-500">Employee</label><select name="employee_id" class="mt-2 block w-full rounded-md border-slate-300 py-2 text-sm"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected($employeeId === $employee->id)>{{ $employee->name }} · {{ ucfirst($employee->getRoleNames()->first() ?: $employee->role) }}</option>@endforeach</select></div><div class="flex items-end gap-2"><button class="rounded-md bg-slate-800 px-5 py-2 text-sm font-semibold text-white">Apply Filter</button><a href="{{ route('reports.product-supplier-sales') }}" class="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600">Reset</a></div></form>

    <section class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Invoices</p><p class="mt-2 text-2xl font-black">{{ number_format($invoiceCount) }}</p></div><div class="rounded-xl border border-indigo-100 bg-indigo-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-indigo-500">Net sales</p><p class="mt-2 text-xl font-black text-indigo-800">৳{{ number_format($totalSales, 2) }}</p></div><div class="rounded-xl border border-amber-100 bg-amber-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-amber-600">Cost of sales</p><p class="mt-2 text-xl font-black text-amber-800">৳{{ number_format($totalCost, 2) }}</p></div><div class="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-emerald-600">Gross profit</p><p class="mt-2 text-xl font-black text-emerald-800">৳{{ number_format($totalSales - $totalCost, 2) }}</p></div></section>

    <section class="mb-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-black text-slate-900">Medicine-wise Sales</h2><p class="mt-1 text-sm text-slate-500">Each row identifies the exact supplier batch used for the sale.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3.5">Medicine</th><th class="px-5 py-3.5">Category</th><th class="px-5 py-3.5">Supplier</th><th class="px-5 py-3.5 text-right">Sold units</th><th class="px-5 py-3.5 text-right">Pieces</th><th class="px-5 py-3.5 text-right">Sales</th><th class="px-5 py-3.5 text-right">Cost</th><th class="px-5 py-3.5 text-right">Profit</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($products as $product)<tr><td class="px-5 py-3.5"><p class="font-bold text-slate-800">{{ $product->product_name }}</p><p class="mt-0.5 text-xs text-slate-500">{{ $product->generic_name ?: 'No generic' }}@if($product->barcode) · {{ $product->barcode }}@endif</p></td><td class="px-5 py-3.5 capitalize text-slate-600">{{ $product->category ?: '—' }}</td><td class="px-5 py-3.5 font-semibold text-slate-700">{{ $product->supplier_name }}</td><td class="px-5 py-3.5 text-right">{{ number_format($product->sale_units) }}</td><td class="px-5 py-3.5 text-right">{{ number_format($product->pieces_sold) }}</td><td class="px-5 py-3.5 text-right font-semibold text-indigo-700">৳{{ number_format($product->sales_amount, 2) }}</td><td class="px-5 py-3.5 text-right">৳{{ number_format($product->cost_amount, 2) }}</td><td class="px-5 py-3.5 text-right font-bold text-emerald-700">৳{{ number_format($product->sales_amount - $product->cost_amount, 2) }}</td></tr>@empty<tr><td colspan="8" class="px-5 py-12 text-center text-slate-500">No product sales found for this period.</td></tr>@endforelse</tbody></table></div></section>

    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-black text-slate-900">Supplier-wise Sales</h2><p class="mt-1 text-sm text-slate-500">Revenue attributed to the supplier of the batch sold.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3.5">Supplier</th><th class="px-5 py-3.5 text-right">Medicines</th><th class="px-5 py-3.5 text-right">Sold units</th><th class="px-5 py-3.5 text-right">Pieces</th><th class="px-5 py-3.5 text-right">Sales</th><th class="px-5 py-3.5 text-right">Cost</th><th class="px-5 py-3.5 text-right">Profit</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($suppliers as $supplier)<tr><td class="px-5 py-3.5 font-bold text-slate-800">{{ $supplier->supplier_name }}</td><td class="px-5 py-3.5 text-right">{{ number_format($supplier->product_count) }}</td><td class="px-5 py-3.5 text-right">{{ number_format($supplier->sale_units) }}</td><td class="px-5 py-3.5 text-right">{{ number_format($supplier->pieces_sold) }}</td><td class="px-5 py-3.5 text-right font-semibold text-indigo-700">৳{{ number_format($supplier->sales_amount, 2) }}</td><td class="px-5 py-3.5 text-right">৳{{ number_format($supplier->cost_amount, 2) }}</td><td class="px-5 py-3.5 text-right font-bold text-emerald-700">৳{{ number_format($supplier->sales_amount - $supplier->cost_amount, 2) }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">No supplier sales found for this period.</td></tr>@endforelse</tbody></table></div></section>
</x-app-layout>
