@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label class="text-sm font-semibold text-slate-700">Customer name <span class="text-rose-500">*</span></label><input name="name" value="{{ old('name', $customer->name ?? '') }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('name')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Customer type <span class="text-rose-500">*</span></label><select name="customer_type" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><option value="retail" @selected(old('customer_type', $customer->customer_type ?? 'retail') === 'retail')>Retail Customer</option><option value="wholesale" @selected(old('customer_type', $customer->customer_type ?? '') === 'wholesale')>Wholesale Customer</option></select><x-input-error :messages="$errors->get('customer_type')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Phone <span class="text-rose-500">*</span></label><input name="phone" value="{{ old('phone', $customer->phone ?? '') }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('phone')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Email</label><input type="email" name="email" value="{{ old('email', $customer->email ?? '') }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('email')" class="mt-2"/></div>
    <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Address</label><textarea name="address" rows="3" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500">{{ old('address', $customer->address ?? '') }}</textarea></div>
</div>
@if(isset($customer) && (float)$customer->due_balance > 0)<div class="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Outstanding balance:</strong> ৳{{ number_format($customer->due_balance, 2) }}</div>@endif
<label class="mt-5 flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $customer->is_active ?? true)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500">Active</label>
<div class="mt-6 flex gap-3"><a href="{{ route('customers.index') }}" class="rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</a><button class="rounded-md bg-gradient-to-r from-[#4165dd] to-[#4432f2] px-5 py-2.5 text-sm font-semibold text-white shadow">{{ isset($customer) ? 'Update Customer' : 'Save Customer' }}</button></div>
