<x-app-layout>
    <x-slot name="header"><h1 class="text-xl font-bold text-slate-900">Dealer-End Sale Entry</h1></x-slot>
    <form method="POST" action="{{ route('dealer-sales.store') }}" x-data="{items:[{product:'',qty:1,price:0,commission:0}],add(){this.items.push({product:'',qty:1,price:0,commission:0})},remove(i){this.items.splice(i,1)}}">
        @csrf
        <div class="space-y-5">
            <section class="rounded-xl border border-teal-200 bg-white"><div class="bg-[#1fafa0] px-5 py-3 text-sm font-semibold text-white">Dealer Sale</div><div class="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-4">
                <label class="text-sm font-semibold">Sale Date<input type="date" name="sale_date" value="{{ old('sale_date',now()->format('Y-m-d')) }}" class="mt-2 block w-full rounded border-slate-300"></label>
                <label class="text-sm font-semibold">Sale No<input value="{{ $nextSaleNo }}" readonly class="mt-2 block w-full rounded border-slate-300 bg-slate-100"></label>
                <label class="text-sm font-semibold">Dealer <a href="{{ route('dealers.create') }}" class="font-normal text-teal-700">⊕ Add New</a><select name="dealer_id" required class="mt-2 block w-full rounded border-slate-300"><option value="">[Select]</option>@foreach($dealers as $dealer)<option value="{{ $dealer->id }}">{{ $dealer->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold">Mode of Sale<select name="mode_of_sale" class="mt-2 block w-full rounded border-slate-300"><option value="cash">Cash</option><option value="credit">Credit</option></select></label>
                <label class="text-sm font-semibold lg:col-span-2">Customer <span class="font-normal text-teal-700">⊕ Add New</span><select name="customer_id" class="mt-2 block w-full rounded border-slate-300"><option value="">[Select]</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold">Tentative Delivery Date<input type="date" name="tentative_delivery_date" class="mt-2 block w-full rounded border-slate-300"></label>
                <label class="text-sm font-semibold">Delivery Point <span class="font-normal"><input name="transfer_from_other" value="1" type="checkbox"> Transfer from other</span><input name="delivery_point" class="mt-2 block w-full rounded border-slate-300" placeholder="[Select]"></label>
                <label class="text-sm font-semibold">Sales Person<select name="sales_person_id" class="mt-2 block w-full rounded border-slate-300"><option value="">[Select]</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold">Product Manager<select name="product_manager_id" class="mt-2 block w-full rounded border-slate-300"><option value="">[Select]</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold lg:col-span-2">Remarks<input name="remarks" class="mt-2 block w-full rounded border-slate-300"></label>
            </div></section>
            <section class="rounded-xl border border-teal-200 bg-white"><div class="bg-[#1fafa0] px-5 py-3 text-sm font-semibold text-white">Vehicle Info</div><div class="p-5"><label class="text-sm font-semibold">Segment<select class="ml-3 rounded border-slate-300"><option>[Select Segment]</option>@foreach($segments as $segment)<option>{{ $segment->name }}</option>@endforeach</select></label></div><div class="overflow-x-auto px-5 pb-5"><table class="w-full min-w-[820px] text-sm"><thead class="bg-sky-500 text-white"><tr><th class="p-2 text-left">Product</th><th>Color</th><th>Qty</th><th>Price</th><th>Comm Per Unit</th><th>Amount</th><th></th></tr></thead><tbody><template x-for="(item,i) in items" :key="i"><tr class="border-b"><td><select :name="`items[${i}][product_id]`" x-model="item.product" @change="item.price=Number($event.target.options[$event.target.selectedIndex].dataset.p||0)" class="w-full border"><option value="">[Select]</option>@foreach($products as $product)<option value="{{ $product->id }}" data-p="{{ $product->selling_price }}">{{ $product->name }}</option>@endforeach</select><select :name="`items[${i}][segment_id]`" class="mt-1 w-full border"><option value="">Segment</option>@foreach($segments as $segment)<option value="{{ $segment->id }}">{{ $segment->name }}</option>@endforeach</select></td><td><input :name="`items[${i}][color]`" class="w-full border"></td><td><input :name="`items[${i}][quantity]`" x-model.number="item.qty" type="number" min="1" class="w-full border"></td><td><input :name="`items[${i}][price]`" x-model.number="item.price" type="number" min="0" class="w-full border"></td><td><input :name="`items[${i}][commission_per_unit]`" x-model.number="item.commission" type="number" min="0" class="w-full border"></td><td class="p-2 font-medium" x-text="(item.qty*item.price).toFixed(2)"></td><td><button type="button" @click="remove(i)" x-show="items.length>1" class="rounded bg-rose-50 px-2 text-rose-700">×</button></td></tr></template></tbody></table><div class="mt-2 flex items-center justify-between"><button type="button" @click="add" class="rounded bg-sky-100 px-3 py-2 text-sky-800">+ Add item</button><span class="text-sm font-semibold">Total Qty: <span x-text="items.reduce((total,item)=>total+Number(item.qty||0),0)"></span> &nbsp; Total Value: <span x-text="items.reduce((total,item)=>total+(Number(item.qty||0)*Number(item.price||0)),0).toFixed(2)"></span></span></div></div></section>
            <section class="rounded-xl border border-teal-200 bg-white"><div class="bg-[#1fafa0] px-5 py-3 text-sm font-semibold text-white">Cost &amp; Payment Info</div><div class="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-4"><label class="text-sm font-semibold">Booking/Paid Amount<input name="paid_amount" value="0" class="mt-2 block w-full rounded border-slate-300 bg-slate-100"></label><label class="text-sm font-semibold">Payment Date<input name="payment_date" type="date" class="mt-2 block w-full rounded border-slate-300"></label><label class="text-sm font-semibold">Mode of Payment<select name="payment_mode" class="mt-2 block w-full rounded border-slate-300"><option value="cash">Cash</option><option value="bank">Bank</option><option value="cheque">Cheque</option></select></label><label class="text-sm font-semibold">Booking Place<input name="booking_place" class="mt-2 block w-full rounded border-slate-300" placeholder="[Select]"></label></div></section>
        </div>
        <div class="mt-6 flex gap-3"><button class="rounded bg-[#1f7d88] px-5 py-2.5 font-semibold text-white">Save</button><a href="{{ route('dealer-sales.index') }}" class="crm-cancel-button rounded px-5 py-2.5">Cancel</a></div>
    </form>
</x-app-layout>
