@csrf
<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
    <div><label class="text-sm font-semibold text-slate-700">Full name <span class="text-rose-500">*</span></label><input name="name" value="{{ old('name', $employee->name ?? '') }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('name')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Email address <span class="text-rose-500">*</span></label><input type="email" name="email" value="{{ old('email', $employee->email ?? '') }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('email')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Phone</label><input name="phone" value="{{ old('phone', $employee->phone ?? '') }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('phone')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Role <span class="text-rose-500">*</span></label><select name="role" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><option value="">Select role</option>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(old('role', isset($employee) ? $employee->getRoleNames()->first() : 'cashier') === $role->name)>{{ ucfirst($role->name) }}</option>@endforeach</select><x-input-error :messages="$errors->get('role')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Designation</label><input name="designation" value="{{ old('designation', $employee->designation ?? '') }}" placeholder="Example: Senior Cashier" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"></div>
    <div><label class="text-sm font-semibold text-slate-700">Joining date <span class="text-rose-500">*</span></label><input type="date" name="joining_date" value="{{ old('joining_date', isset($employee) && $employee->joining_date ? $employee->joining_date->toDateString() : now()->toDateString()) }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('joining_date')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Monthly salary (৳) <span class="text-rose-500">*</span></label><input type="number" min="0" step="0.01" name="salary" value="{{ old('salary', $employee->salary ?? 0) }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('salary')" class="mt-2"/></div>
    <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Address</label><input name="address" value="{{ old('address', $employee->address ?? '') }}" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"></div>
</div>
<div class="mt-6 grid gap-5 rounded-lg border border-slate-200 bg-slate-50 p-5 md:grid-cols-2">
    <div><label class="text-sm font-semibold text-slate-700">{{ isset($employee) ? 'New password' : 'Login password' }} {{ isset($employee) ? '' : '*' }}</label><input type="password" name="password" {{ isset($employee) ? '' : 'required' }} autocomplete="new-password" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><p class="mt-1 text-xs text-slate-400">{{ isset($employee) ? 'Leave blank to keep the current password.' : 'At least 8 characters.' }}</p><x-input-error :messages="$errors->get('password')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Confirm password {{ isset($employee) ? '' : '*' }}</label><input type="password" name="password_confirmation" {{ isset($employee) ? '' : 'required' }} autocomplete="new-password" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"></div>
</div>
<label class="mt-5 flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $employee->is_active ?? true)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500">Active employee</label>
<div class="mt-6 flex gap-3"><a href="{{ route('employees.index') }}" class="rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</a><button class="rounded-md bg-gradient-to-r from-[#4165dd] to-[#4432f2] px-5 py-2.5 text-sm font-semibold text-white shadow hover:opacity-95">{{ isset($employee) ? 'Update Employee' : 'Save Employee' }}</button></div>
