@csrf
<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
    <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Medicine name <span class="text-rose-500">*</span></label><input name="name" value="{{ old('name', $product->name ?? '') }}" required placeholder="Example: Napa 500 mg Tablet" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('name')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Medicine category <span class="text-rose-500">*</span></label><select name="category" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500">@foreach(['tablet', 'capsule', 'syrup', 'suspension', 'injection', 'drops', 'cream', 'ointment', 'gel', 'inhaler', 'suppository', 'powder', 'sachet', 'other'] as $category)<option value="{{ $category }}" @selected(old('category', $product->category ?? 'tablet') === $category)>{{ ucfirst($category) }}</option>@endforeach</select><x-input-error :messages="$errors->get('category')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Barcode</label><input name="barcode" value="{{ old('barcode', $product->barcode ?? '') }}" placeholder="Scan or type barcode" class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('barcode')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Generic name</label><select name="generic_name_id" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><option value="">Select generic</option>@foreach($genericNames as $genericName)<option value="{{ $genericName->id }}" @selected(old('generic_name_id', $product->generic_name_id ?? '') == $genericName->id)>{{ $genericName->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('generic_name_id')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Base stock unit <span class="text-rose-500">*</span></label><select name="unit" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500">@foreach(['piece', 'bottle', 'tube', 'vial', 'sachet'] as $unit)<option value="{{ $unit }}" @selected(old('unit', $product->unit ?? 'piece') === $unit)>{{ ucfirst($unit) }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-400">For tablets/capsules, use Piece.</p></div>
    <div><label class="text-sm font-semibold text-slate-700">Pieces per strip <span class="text-rose-500">*</span></label><input type="number" min="1" name="pieces_per_strip" value="{{ old('pieces_per_strip', $product->pieces_per_strip ?? 10) }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('pieces_per_strip')" class="mt-2"/></div>
    <div><label class="text-sm font-semibold text-slate-700">Low-stock alert at <span class="text-rose-500">*</span></label><input type="number" min="0" name="reorder_level" value="{{ old('reorder_level', $product->reorder_level ?? 10) }}" required class="mt-2 block w-full rounded-md border-slate-300 px-3 py-2.5 text-sm focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get('reorder_level')" class="mt-2"/></div>
</div>
<div class="mt-5 rounded-lg border border-blue-100 bg-blue-50 p-4"><p class="text-sm font-bold text-blue-900">Allowed POS selling units</p><div class="mt-3 flex flex-wrap gap-6"><label class="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="sell_by_piece" value="1" @checked(old('sell_by_piece', $product->sell_by_piece ?? true)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500">Sell single piece</label><label class="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="sell_by_strip" value="1" @checked(old('sell_by_strip', $product->sell_by_strip ?? false)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500">Sell full strip</label></div><x-input-error :messages="$errors->get('sell_by_piece')" class="mt-2"/></div>
<label class="mt-5 flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->is_active ?? true)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500">Active</label>
<div class="mt-6 flex gap-3"><a href="{{ route('products.index') }}" class="rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</a><button class="rounded-md bg-gradient-to-r from-[#4165dd] to-[#4432f2] px-5 py-2.5 text-sm font-semibold text-white shadow hover:opacity-95">{{ isset($product) ? 'Update Medicine' : 'Save Medicine' }}</button></div>
