<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#315df4]">Accounts</p><h1 class="mt-1 text-2xl font-black text-slate-900">New {{ ucfirst($type) }} Voucher</h1><p class="mt-1 text-sm text-slate-500">{{ match($type) { 'debit' => 'Payment: debit the receiving account and credit cash/bank.', 'credit' => 'Receipt: debit cash/bank and credit the receiving account.', 'journal' => 'Enter balanced debit and credit adjustment lines.', default => 'Transfer an amount from one cash, bank, or mobile account to another.' } }}</p></div></x-slot>
    @if($type === 'journal')
        <form method="POST" action="{{ route('vouchers.store', $type) }}" x-data="{ lines: Array.from({ length: 5 }, () => ({ debit: '', credit: '' })), total(key) { return this.lines.reduce((sum, line) => sum + (Number(line[key]) || 0), 0).toFixed(2) } }">@csrf
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="bg-gradient-to-r from-[#4165dd] to-[#2947bd] px-5 py-3 text-sm font-semibold text-white">Journal Voucher Information</div><div class="grid gap-5 p-6 md:grid-cols-2"><div><label class="text-sm font-semibold text-slate-700">Voucher Date *</label><input type="date" name="voucher_date" value="{{ old('voucher_date', now()->toDateString()) }}" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-slate-700">Narration</label><input name="narration" value="{{ old('narration') }}" placeholder="Reason for adjustment" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></div></div><div class="overflow-x-auto border-t border-slate-200"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Account</th><th class="px-5 py-3 text-right">Debit</th><th class="px-5 py-3 text-right">Credit</th><th class="px-5 py-3">Line Note</th></tr></thead><tbody class="divide-y divide-slate-100"><template x-for="(line, index) in lines" :key="index"><tr><td class="px-5 py-3"><select :name="`entries[${index}][account_id]`" class="block w-full rounded-md border-slate-300 py-2 text-sm"><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></td><td class="px-5 py-3"><input type="number" min="0" step="0.01" x-model="line.debit" :name="`entries[${index}][debit]`" class="block w-32 rounded-md border-slate-300 py-2 text-right text-sm"></td><td class="px-5 py-3"><input type="number" min="0" step="0.01" x-model="line.credit" :name="`entries[${index}][credit]`" class="block w-32 rounded-md border-slate-300 py-2 text-right text-sm"></td><td class="px-5 py-3"><input :name="`entries[${index}][note]`" placeholder="Optional" class="block w-full rounded-md border-slate-300 py-2 text-sm"></td></tr></template></tbody><tfoot class="border-t-2 border-slate-400 bg-slate-50"><tr><th class="px-5 py-4 text-right">Total</th><th class="px-5 py-4 text-right" x-text="'৳' + total('debit')"></th><th class="px-5 py-4 text-right" x-text="'৳' + total('credit')"></th><th></th></tr></tfoot></table></div><div class="flex justify-between gap-3 border-t border-slate-100 px-6 py-5"><button type="button" @click="lines.push({ debit: '', credit: '' })" class="rounded-md border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-bold text-indigo-700">+ Add Line</button><div class="flex gap-3"><a href="{{ route('vouchers.index', $type) }}" class="rounded-md border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-lg bg-[#2d63e9] px-6 py-2.5 text-sm font-bold text-white">Save Journal Voucher</button></div></div></section>
        </form>
    @else
        @php($sourceLabel = $type === 'debit' ? 'Paid From (Credit)' : ($type === 'credit' ? 'Received Into (Debit)' : 'Transfer From (Credit)'))
        @php($targetLabel = $type === 'debit' ? 'Debit To' : ($type === 'credit' ? 'Credit To' : 'Transfer To (Debit)'))
        @php($selectableAccounts = $type === 'contra' ? $cashAccounts : $accounts)
        <form method="POST" action="{{ route('vouchers.store', $type) }}">@csrf<section class="max-w-4xl overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="bg-gradient-to-r from-[#4165dd] to-[#2947bd] px-5 py-3 text-sm font-semibold text-white">{{ ucfirst($type) }} Voucher Information</div><div class="grid gap-5 p-6 md:grid-cols-2"><div><label class="text-sm font-semibold text-slate-700">Voucher Date *</label><input type="date" name="voucher_date" value="{{ old('voucher_date', now()->toDateString()) }}" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-slate-700">Amount *</label><input type="number" name="amount" min="0.01" step="0.01" value="{{ old('amount') }}" required placeholder="0.00" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-slate-700">{{ $sourceLabel }} *</label><select name="cash_account_id" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select account</option>@foreach($selectableAccounts as $account)<option value="{{ $account->id }}" @selected(old('cash_account_id') == $account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div><div><label class="text-sm font-semibold text-slate-700">{{ $targetLabel }} *</label><select name="account_id" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select account</option>@foreach($selectableAccounts as $account)<option value="{{ $account->id }}" @selected(old('account_id') == $account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div><div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Narration</label><textarea name="narration" rows="3" placeholder="Describe this voucher" class="mt-2 block w-full rounded-md border-slate-300 text-sm">{{ old('narration') }}</textarea></div></div><div class="flex justify-end gap-3 border-t border-slate-100 px-6 py-5"><a href="{{ route('vouchers.index', $type) }}" class="rounded-md border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-lg bg-[#2d63e9] px-6 py-2.5 text-sm font-bold text-white">Save {{ ucfirst($type) }} Voucher</button></div></section></form>
    @endif
</x-app-layout>
