<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h1 class="text-xl font-bold text-slate-900">Sales (Product Wise)</h1><a href="{{ route('customer-sales.create') }}" class="rounded bg-[#1f7d88] px-4 py-2 text-sm font-semibold text-white">Customer Sale Entry</a></div></x-slot>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <form class="grid gap-3 border-b p-4 lg:grid-cols-6">
            <select name="segment" class="rounded border-slate-300 text-sm"><option value="">[Select Segment]</option>@foreach($segments as $segment)<option value="{{ $segment->id }}" @selected(($filters['segment']??'') == $segment->id)>{{ $segment->name }}</option>@endforeach</select>
            <select name="product" class="rounded border-slate-300 text-sm"><option value="">[Select Product]</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(($filters['product']??'') == $product->id)>{{ $product->name }}</option>@endforeach</select>
            <select name="dealer" class="rounded border-slate-300 text-sm"><option value="">[Select Dealer]</option>@foreach($dealers as $dealer)<option value="{{ $dealer }}" @selected(($filters['dealer']??'') === $dealer)>{{ $dealer }}</option>@endforeach</select>
            <select name="sales_person" class="rounded border-slate-300 text-sm"><option value="">[Select Sales Person]</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['sales_person']??'') == $user->id)>{{ $user->name }}</option>@endforeach</select>
            <input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="rounded border-slate-300 text-sm">
            <input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="rounded border-slate-300 text-sm">
            <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Invoice No/Customer/Engine No/Chassis No" class="rounded border-slate-300 text-sm lg:col-span-5">
            <div class="flex gap-2"><button class="rounded bg-[#1f7d88] px-4 py-2 text-sm font-semibold text-white">Search</button><a href="{{ route('customer-sales.index') }}" class="rounded bg-slate-100 px-3 py-2 text-sm">Reset</a></div>
        </form>
        <div class="p-4 text-sm font-bold">Total Sale Qty: {{ $sales->sum('quantity') }} &nbsp; Total Amount: ৳{{ number_format($sales->sum('final_price'), 2) }}</div>
        <div class="overflow-x-auto"><table class="w-full min-w-[1400px] text-left text-sm"><thead class="border-y bg-slate-50 text-xs uppercase text-slate-700"><tr><th class="p-3">SL.</th><th class="p-3">Invoice ID &amp; Date</th><th class="p-3">Customer</th><th class="p-3">Executed By</th><th class="p-3">Dealer</th><th class="p-3">Model &amp; Color</th><th class="p-3">Engine No</th><th class="p-3">Chassis No</th><th class="p-3">Delivery Date</th><th class="p-3 text-center">Qty</th><th class="p-3 text-right">Total Amount</th><th class="p-3">DO</th><th class="p-3">Image</th></tr></thead><tbody class="divide-y">@forelse($sales as $sale)<tr class="align-top hover:bg-slate-50"><td class="p-3">{{ $sales->firstItem() + $loop->index }}</td><td class="p-3 font-medium">{{ $sale->sale_no }}<br><span class="text-xs font-normal text-slate-500">{{ $sale->sale_date->format('d-m-y') }}</span></td><td class="p-3">{{ $sale->customer_name ?? '—' }}<br><span class="text-xs text-slate-500">{{ $sale->customer_phone }}</span></td><td class="p-3">{{ $sale->sales_person_name ?? '—' }}</td><td class="p-3">{{ $sale->dealer ?: 'Self' }}</td><td class="p-3">{{ $sale->product_name ?? '—' }}<br><span class="text-xs text-slate-500">{{ $sale->color ?: '—' }}</span></td><td class="p-3 text-slate-500">—</td><td class="p-3 text-slate-500">—</td><td class="p-3">{{ $sale->tentative_delivery_date?->format('d-m-y') ?? '—' }}</td><td class="p-3 text-center">{{ $sale->quantity }}</td><td class="p-3 text-right font-semibold">৳{{ number_format($sale->final_price, 2) }}</td><td class="p-3">@if($sale->delivery_point)<span class="text-teal-700">DO Generate</span>@else<span class="text-slate-400">—</span>@endif</td><td class="p-3"><button type="button" class="text-teal-700 hover:underline">Upload Image</button></td></tr>@empty<tr><td colspan="13" class="p-10 text-center text-slate-500">No sales found.</td></tr>@endforelse</tbody></table></div>
        @if($sales->hasPages())<div class="border-t p-4">{{ $sales->links() }}</div>@endif
    </section>
</x-app-layout>
