<aside :class="{ 'translate-x-0': mobileNavOpen }" class="fixed inset-y-0 left-0 z-30 flex w-72 -translate-x-full flex-col overflow-y-auto bg-[#171E2E] text-white shadow-2xl transition-transform duration-300 lg:w-60 lg:translate-x-0 lg:shadow-none">
    <div class="flex h-20 shrink-0 items-center gap-3 border-b border-white/10 px-5"><div class="grid h-12 w-12 place-items-center rounded-xl bg-white text-lg font-black text-[#1736c7] shadow">CR</div><div class="flex-1"><p class="text-lg font-bold">AutoCRM</p><p class="text-xs text-indigo-300">Automobile sales</p></div><button type="button" @click="mobileNavOpen = false" class="text-xl lg:hidden">×</button></div>
    <nav class="space-y-1 px-3 py-5 text-sm">
        @can('dashboard.view')<a href="{{ route('dashboard') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('dashboard') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold' : 'text-indigo-100 hover:bg-white/10' }}"><span>⌂</span>Dashboard</a>@endcan
        @if(auth()->user()->canAny(['activities.manage','activity-setup.manage','leads.manage','todos.manage','contacts.manage','organizations.manage','performance-reports.view']))
        <p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Customer Relationship</p>
        @if(auth()->user()->canAny(['activities.manage','activity-setup.manage']))<div x-data="{ open: {{ request()->routeIs('activities.*','activity-setup.*') ? 'true' : 'false' }} }"><button type="button" @click="open=!open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10"><span>◈ Activity</span><span class="inline-block text-lg leading-none transition-transform duration-200 ease-out" :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" x-transition class="ml-6 border-l border-white/10 pl-2">@can('activities.manage')<a href="{{route('activities.create')}}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Add Activity</a><a href="{{route('activities.index')}}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Activity List</a>@endcan @can('activity-setup.manage')<a href="{{route('activity-setup.index')}}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Activity Setup</a>@endcan</div></div>@endif
        @can('leads.manage')<a href="{{route('leads.index')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">♧ Leads</a>@endcan
        @can('todos.manage')<a href="{{route('todos.index')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">✓ Task To-Do</a>@endcan
        @if(auth()->user()->canAny(['contacts.manage','organizations.manage']))<div x-data="{ open: {{ request()->routeIs('contacts.*','organizations.*') ? 'true' : 'false' }} }"><button type="button" @click="open=!open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10"><span>♙ Contact</span><span class="inline-block text-lg leading-none transition-transform duration-200 ease-out" :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" x-transition class="ml-6 border-l border-white/10 pl-2">@can('contacts.manage')<a href="{{route('contacts.create')}}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Add Contact</a><a href="{{route('contacts.index')}}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Contact List</a>@endcan @can('organizations.manage')<a href="{{route('organizations.index')}}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Organizations</a>@endcan</div></div>@endif
        @can('performance-reports.view')<a href="{{route('performance.index')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">◫ Performance Report</a>@endcan
        @endif
        @if(auth()->user()->canAny(['events.manage','budgets.manage']))<p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Promotion &amp; Campaign</p>@can('events.manage')<a href="{{route('events.create')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">★ Event Add</a><a href="{{route('events.index')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">☷ Events</a>@endcan @can('budgets.manage')<a href="{{route('budgets.create')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">৳ Budget Add</a><a href="{{route('budgets.index')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">☷ Budgets</a>@endcan @endif
        @can('settings.manage')<p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Administration</p><a href="{{route('roles.index')}}" class="flex gap-3 rounded-md px-3 py-2.5 text-indigo-100 hover:bg-white/10">⚙ Roles &amp; Permissions</a>@endcan
    </nav>
    <form method="POST" action="{{ route('logout') }}" class="mx-3 mt-auto border-t border-white/10 pt-4">@csrf<button class="w-full rounded-md px-3 py-2.5 text-left text-sm text-indigo-200 hover:bg-white/10">↪ Sign out</button></form>
</aside>
