<aside :class="{ 'translate-x-0': mobileNavOpen }" class="fixed inset-y-0 left-0 z-30 flex w-72 -translate-x-full flex-col overflow-y-auto bg-[#171E2E] text-white shadow-2xl transition-transform duration-300 lg:w-64 lg:translate-x-0 lg:shadow-none">
    <div class="flex h-20 shrink-0 items-center gap-3 border-b border-white/10 px-5"><div class="grid h-11 w-11 place-items-center rounded-xl bg-white text-lg font-black text-[#1736c7] shadow">CR</div><div class="flex-1"><p class="text-lg font-bold">AutoCRM</p><p class="text-xs text-indigo-300">ERP &amp; CRM</p></div><button type="button" @click="mobileNavOpen = false" class="text-xl lg:hidden">×</button></div>
    <nav class="space-y-1 px-3 py-4 text-sm">
        @can('dashboard.view')<a href="{{ route('dashboard') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('dashboard') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold' : 'text-indigo-100 hover:bg-white/10' }}"><span>⌂</span>Dashboard</a>@endcan

        <p class="px-3 pb-1 pt-4 text-[10px] font-bold uppercase tracking-[.16em] text-indigo-400">Phase 1 · Core Admin &amp; Master Setup</p>
        @if(auth()->user()->canAny(['config.roles.manage','config.employees.manage','config.users.manage','config.stores.manage','config.store-positions.manage']))
        <div x-data="{ open: {{ request()->is('admin/roles*') || request()->is('admin/employees*') || request()->is('admin/stores*') || request()->is('admin/store-positions*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>1. Config</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3">@can('config.roles.manage')<a href="{{ route('roles.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">User Role</a>@endcan @can('config.employees.manage')<a href="{{ route('employees.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Employee</a><a href="{{ route('employees.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">New User / User</a>@endcan @can('config.stores.manage')<a href="{{ route('stores.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Store</a>@endcan @can('config.store-positions.manage')<a href="{{ route('store-positions.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Store Position</a>@endcan</div></div>
        @endif
        @can('system-settings.manage')
        <div x-data="{ open: {{ request()->is('admin/system-settings*') || request()->is('admin/products*') || request()->is('crm/activity-setup*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>2. System Settings</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3"><a href="{{ route('system-settings.index') }}#lead-sources" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Lead Source</a><a href="{{ route('system-settings.index') }}#pipeline-stages" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Lead Pipeline Stages</a><a href="{{ route('system-settings.index') }}#departments" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Department</a><a href="{{ route('products.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Products</a><a href="{{ route('activity-setup.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Activity Type / Sub Type</a><a href="{{ route('stores.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Showroom / Warehouse</a></div></div>
        @endcan
        @if(auth()->user()->canAny(['contacts.manage','organizations.manage','leads.manage','activities.manage']))
        <div x-data="{ open: {{ request()->is('crm/*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>3. Customer Relationship</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3">@can('contacts.manage')<a href="{{ route('contacts.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Contact Add / Contact</a>@endcan @can('organizations.manage')<a href="{{ route('organizations.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Organization</a>@endcan @can('leads.manage')<a href="{{ route('leads.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Lead Add / Leads</a>@endcan @can('activities.manage')<a href="{{ route('activities.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Activity Add</a>@endcan</div></div>
        @endif
        @if(auth()->user()->canAny(['products.view','products.manage','suppliers.manage']))
        <div x-data="{ open: {{ request()->is('admin/products*') || request()->is('admin/suppliers*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>4. Item Inventory</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3">@can('products.view')<a href="{{ route('products.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Item Category / Item</a>@endcan @can('suppliers.manage')<a href="{{ route('suppliers.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Supplier</a>@endcan</div></div>
        @endif

        <p class="px-3 pb-1 pt-4 text-[10px] font-bold uppercase tracking-[.16em] text-indigo-400">Phase 2 · Inventory &amp; Distribution</p>
        @if(auth()->user()->canAny(['purchases.manage','reports.view']))
        <div x-data="{ open: {{ request()->is('admin/purchases*') || request()->is('admin/reports/stock') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>5. Stock &amp; Inventory</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3"><span class="block cursor-not-allowed px-3 py-2 text-indigo-400/60">Product Transfer · Soon</span>@can('purchases.manage')<a href="{{ route('purchases.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Product Receive</a>@endcan @can('reports.view')<a href="{{ route('reports.stock') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Stock Summary</a>@endcan</div></div>
        @endif
        @can('sales.manage')<div x-data="{ open: {{ request()->is('sales/dealer*') || request()->is('sales/documents*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>6. Dealer &amp; Delivery</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3"><span class="block cursor-not-allowed px-3 py-2 text-indigo-400/60">Add New Dealer / Dealer List · Soon</span><a href="{{ route('dealer-sales.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Delivery Order</a><a href="{{ route('sales-documents.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Delivery Challan</a></div></div>@endcan

        <p class="px-3 pb-1 pt-4 text-[10px] font-bold uppercase tracking-[.16em] text-indigo-400">Phase 3 · Revenue Operations</p>
        @if(auth()->user()->canAny(['sales-targets.manage','sales.manage','sales.return']))
        <div x-data="{ open: {{ request()->is('sales/*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>7. Order &amp; Sales</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3">@can('sales-targets.manage')<a href="{{ route('sales-targets.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Sales Target</a>@endcan @can('sales.manage')<a href="{{ route('customer-sales.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Customer Sale Entry</a><a href="{{ route('sales-collections.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Sales Collection</a>@endcan @can('sales.return')<a href="{{ route('sales-returns.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Sale Return</a>@endcan</div></div>
        @endif
        @if(auth()->user()->canAny(['budgets.manage','events.manage','bulk-sms.manage']))<div x-data="{ open: {{ request()->is('promotion/*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>8. Promotion &amp; Campaign</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3">@can('budgets.manage')<a href="{{ route('budgets.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Budgets</a>@endcan @can('events.manage')<a href="{{ route('events.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Events</a>@endcan @can('bulk-sms.manage')<a href="{{ route('bulk-sms.create') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Bulk SMS Blast</a>@endcan</div></div>@endif
        @if(auth()->user()->canAny(['pre-event-plans.manage','agendas.manage','meetings.manage']))<div x-data="{ open: {{ request()->is('planning/*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>9. Meeting &amp; Planning</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3">@can('pre-event-plans.manage')<a href="{{ route('pre-event-plans.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Pre-event Plans</a>@endcan @can('agendas.manage')<a href="{{ route('agendas.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Agenda List</a>@endcan @can('meetings.manage')<a href="{{ route('meetings.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Meetings</a>@endcan</div></div>@endif

        <p class="px-3 pb-1 pt-4 text-[10px] font-bold uppercase tracking-[.16em] text-indigo-400">Phase 4 · Finance &amp; Reporting</p>
        @can('accounts.manage')<div x-data="{ open: {{ request()->is('admin/accounts*') || request()->is('admin/vouchers*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>10. Accounts</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3"><a href="{{ route('accounts.index') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Chart of Accounts</a><a href="{{ route('vouchers.index', 'receipt') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Receive / Payment Entry</a><a href="{{ route('vouchers.index', 'journal') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Journal Vouchers</a></div></div>@endcan
        @can('reports.view')<div x-data="{ open: {{ request()->is('admin/reports*') || request()->is('admin/ledgers*') ? 'true' : 'false' }} }"><button type="button" @click="open = !open" class="flex w-full items-center justify-between rounded-md px-3 py-2.5 font-semibold text-indigo-100 hover:bg-white/10"><span>11. Financial Reports</span><span :class="open ? 'rotate-90' : ''">›</span></button><div x-cloak x-show="open" class="space-y-0.5 pl-3"><span class="block cursor-not-allowed px-3 py-2 text-indigo-400/60">Cash Book / Bank Book · Soon</span><a href="{{ route('ledgers.customers') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Ledgers</a><a href="{{ route('reports.trial-balance') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Trial Balance</a><a href="{{ route('reports.income-statement') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Income Statement</a><a href="{{ route('reports.balance-sheet') }}" class="block rounded px-3 py-2 text-indigo-200 hover:bg-white/10">Balance Sheet</a></div></div>@endcan
    </nav>
    <form method="POST" action="{{ route('logout') }}" class="mx-3 mt-auto border-t border-white/10 pt-4">@csrf<button class="w-full rounded-md px-3 py-2.5 text-left text-sm text-indigo-200 hover:bg-white/10">↪ Sign out</button></form>
</aside>
