<aside :class="{ 'translate-x-0': mobileNavOpen }" class="fixed inset-y-0 left-0 z-30 flex w-72 -translate-x-full flex-col overflow-y-auto bg-[#171E2E] text-white shadow-2xl transition-transform duration-300 ease-out print:hidden lg:w-60 lg:translate-x-0 lg:shadow-none">
    <div class="flex h-20 shrink-0 items-center gap-3 border-b border-white/10 px-5"><div class="grid h-12 w-12 place-items-center rounded-xl bg-white text-lg font-black text-[#1736c7] shadow">Rx</div><div class="flex-1"><p class="text-lg font-bold">MediStock</p><p class="text-xs text-indigo-300">Pharmacy POS</p></div><button type="button" @click="mobileNavOpen = false" class="grid h-9 w-9 place-items-center rounded-lg text-xl text-indigo-100 hover:bg-white/10 lg:hidden" aria-label="Close navigation menu">×</button></div>
    <nav class="space-y-1 px-3 py-5 text-sm">
        @can('dashboard.view')<p class="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Overview</p>
        <a @click="mobileNavOpen = false" href="{{ route('dashboard') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('dashboard') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span class="text-base">⌂</span>Dashboard</a>@endcan
        @can('pos.access')<a href="{{ route('pos.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('pos.index') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>▣</span>Point of Sale</a>
        <a href="{{ route('pos.saved-orders.index', ['status' => 'held']) }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('pos.saved-orders.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>⏸</span>Held Orders &amp; Drafts</a>
        <a href="{{ route('pos.history') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('pos.history', 'sales.show') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>☷</span>POS Sales History</a>@endcan
        @if(auth()->user()->canAny(['suppliers.manage', 'brands.manage', 'generic-names.manage', 'products.view', 'products.manage']))<p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Medicine Setup</p>
        @can('suppliers.manage')
        <a href="{{ route('suppliers.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('suppliers.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>▤</span>Suppliers</a>
        @endcan
        @can('generic-names.manage')
        <a href="{{ route('generic-names.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('generic-names.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◎</span>Generic Names</a>
        @endcan
        @if(auth()->user()->can('products.view') || auth()->user()->can('products.manage'))<a href="{{ route('products.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('products.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>▦</span>Medicines & Stock</a>@endif @endif
        @if(auth()->user()->canAny(['activities.manage', 'leads.manage', 'todos.manage', 'customers.manage']))
        <p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Customer Relationship</p>
        @can('activities.manage')<a href="{{ route('activities.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('activities.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◈</span>Activities</a>@endcan
        @can('leads.manage')<a href="{{ route('leads.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('leads.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>♧</span>Leads</a>@endcan
        @can('todos.manage')<a href="{{ route('todos.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('todos.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>✓</span>Task To-Do</a>@endcan
        @can('customers.manage')<a href="{{ route('customers.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('customers.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>♧</span>Customers</a>@endcan
        @endif
        @if(auth()->user()->canAny(['purchases.manage', 'reports.view']))
        <p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Operations</p>
        @can('purchases.manage')<a href="{{ route('purchases.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('purchases.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>▧</span>Purchases</a>@endcan
        @can('reports.view')
        <a href="{{ route('reports.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('reports.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◫</span>Reports</a>
        @endcan @endif
        @can('accounts.manage')<p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Accounts</p>
        <a href="{{ route('accounts.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('accounts.index', 'accounts.create', 'accounts.store', 'accounts.edit', 'accounts.update', 'accounts.destroy') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>▤</span>Chart of Accounts</a>
        <a href="{{ route('accounts.sub-accounts') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('accounts.sub-accounts') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>└</span>Sub Account List</a>
        <a href="{{ route('accounts.opening-balances.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('accounts.opening-balances.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>৳</span>Opening Balance</a>
        <a href="{{ route('vouchers.index', 'debit') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('vouchers.*') && request()->route('type') === 'debit' ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>↓</span>Debit Voucher</a>
        <a href="{{ route('vouchers.index', 'credit') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('vouchers.*') && request()->route('type') === 'credit' ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>↑</span>Credit Voucher</a>
        <a href="{{ route('vouchers.index', 'journal') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('vouchers.*') && request()->route('type') === 'journal' ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>≡</span>Journal Voucher</a>
        <a href="{{ route('vouchers.index', 'contra') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('vouchers.*') && request()->route('type') === 'contra' ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>⇄</span>Contra Voucher</a>
        <a href="{{ route('party-transactions.index', 'customer_receive') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('party-transactions.*') && request()->route('type') === 'customer_receive' ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>↓</span>Customer Receive</a>
        <a href="{{ route('party-transactions.index', 'supplier_payment') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('party-transactions.*') && request()->route('type') === 'supplier_payment' ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>↑</span>Supplier Payment</a>
        <a href="{{ route('ledgers.customers') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('ledgers.customers') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>≣</span>Customer Ledger</a>
        <a href="{{ route('ledgers.suppliers') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('ledgers.suppliers') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>≣</span>Supplier Ledger</a>
        @can('reports.view')<p class="px-3 pb-1 pt-4 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Financial Reports</p>
        <a href="{{ route('reports.profit-loss') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('reports.profit-loss') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◫</span>Profit &amp; Loss</a>
        <a href="{{ route('reports.trial-balance') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('reports.trial-balance') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◫</span>Trial Balance</a>
        <a href="{{ route('reports.income-statement') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('reports.income-statement') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◫</span>Income Statement</a>
        <a href="{{ route('reports.balance-sheet') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('reports.balance-sheet') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>◫</span>Balance Sheet</a>@endcan
        @endcan
        @can('employees.manage')<p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">Human Resources</p>
        <a href="{{ route('employees.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('employees.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>♙</span>Employees</a>
        <a href="{{ route('attendance.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('attendance.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>✓</span>Attendance</a>
        <a href="{{ route('payrolls.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('payrolls.*', 'salary-payments.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>৳</span>Payroll &amp; Salary</a>
        @endcan
        @can('settings.manage')<p class="px-3 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-indigo-400">System Settings</p><a href="{{ route('roles.index') }}" class="flex items-center gap-3 rounded-md px-3 py-2.5 {{ request()->routeIs('roles.*') ? 'bg-gradient-to-r from-[#3f57ed] to-[#4632f5] font-semibold shadow' : 'text-indigo-100 hover:bg-white/10' }}"><span>⚙</span>Roles &amp; Permissions</a>@endcan
    </nav>
    <form method="POST" action="{{ route('logout') }}" class="mx-3 mt-6 border-t border-white/10 pt-4">@csrf<button class="w-full rounded-md px-3 py-2.5 text-left text-sm text-indigo-200 hover:bg-white/10">↪ Sign out</button></form>
</aside>
