<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#315df4]">Accounts</p><h1 class="mt-1 text-2xl font-black text-slate-900">Chart of Accounts</h1><p class="mt-1 text-sm text-slate-500">Organize the financial structure of your pharmacy.</p></div><a href="{{ route('accounts.create') }}" class="rounded-lg bg-[#2d63e9] px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-[#214fc6]">＋ New Account</a></div>
    </x-slot>
    <div x-data="{ selected: {{ $accounts->first()?->id ?? 'null' }}, accounts: @js($accountData), search: '', open: {} }">
        <section class="mb-5 flex flex-col justify-between gap-4 rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-sm md:flex-row md:items-center"><div class="flex items-center gap-8 text-sm"><span class="text-slate-600"><b class="mr-2 text-lg text-[#2d63e9]">♜</b><strong>{{ $accounts->whereNull('parent_id')->count() }}</strong> account groups</span><span class="text-slate-600"><b class="mr-2 text-lg text-[#2d63e9]">▣</b><strong>{{ $accounts->count() }}</strong> accounts</span></div><div class="relative"><span class="pointer-events-none absolute left-3 top-2.5 text-[#2d63e9]">⌕</span><input x-model="search" placeholder="Search account or code" class="w-full rounded-lg border-slate-300 py-2.5 pl-9 pr-3 text-sm focus:border-[#2d63e9] focus:ring-[#2d63e9] md:w-72"></div></section>
        <div class="grid gap-5 xl:grid-cols-[minmax(0,1.75fr)_minmax(300px,.78fr)]">
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 class="font-bold text-slate-900">Account hierarchy</h2><p class="mt-1 text-xs text-slate-500">Select an account to view details</p></div><button type="button" @click="Object.keys(accounts).forEach((id) => open[id] = true)" class="text-xs font-bold text-[#2d63e9]">Expand all</button></div><div class="max-h-[600px] overflow-auto p-4"><button type="button" @click="selected = null" class="flex w-full items-center gap-2 rounded-lg border-l-4 border-[#2d63e9] bg-[#f4f7ff] px-3 py-2.5 text-left font-bold text-[#17336a]"><span class="text-lg text-[#2d63e9]">▱</span> COA <span class="ml-auto text-xs font-normal text-slate-400">Root</span></button><div class="mt-1">@include('admin.accounts._tree-node', ['nodes' => $accountsByParent->get(null, collect()), 'accountsByParent' => $accountsByParent])</div></div></section>
            <aside class="h-fit rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-[#315df4]">Account details</p><template x-if="selected && accounts[selected]"><div class="mt-4"><div class="grid h-12 w-12 place-items-center rounded-xl bg-[#eef4ff] text-2xl text-[#2d63e9]">▱</div><h2 class="mt-4 text-xl font-black text-slate-900" x-text="accounts[selected].name"></h2><p class="mt-1 text-sm text-slate-500">Review the selected account information.</p><dl class="mt-5 divide-y divide-slate-100 border-y border-slate-100 text-sm"><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Head code</dt><dd class="font-mono font-bold text-slate-800" x-text="accounts[selected].code"></dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Head type</dt><dd class="font-semibold text-slate-800" x-text="accounts[selected].type"></dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Parent head</dt><dd class="text-right font-semibold text-slate-800" x-text="accounts[selected].parent"></dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Use</dt><dd class="font-semibold" :class="accounts[selected].transactional ? 'text-emerald-700' : 'text-slate-600'" x-text="accounts[selected].transactional ? 'Transaction account' : 'Group account'"></dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Status</dt><dd><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="accounts[selected].active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'" x-text="accounts[selected].active ? 'Active' : 'Inactive'"></span></dd></div></dl><div class="mt-5 grid grid-cols-2 gap-2"><a :href="`{{ url('/admin/accounts') }}/${selected}/edit`" class="rounded-lg border border-slate-300 py-2.5 text-center text-sm font-bold text-slate-700">Edit</a><a :href="`{{ route('accounts.create') }}?parent_id=${selected}`" class="rounded-lg bg-[#2d63e9] py-2.5 text-center text-sm font-bold text-white">Add Sub Account</a></div></div></template><template x-if="!selected"><div class="py-16 text-center"><div class="text-3xl text-[#2d63e9]">▱</div><p class="mt-3 font-bold text-slate-800">Chart of Accounts</p><p class="mt-1 text-xs text-slate-500">Select an account in the hierarchy.</p></div></template></aside>
        </div>
    </div>
</x-app-layout>
