<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><h1 class="text-xl font-bold text-slate-900">Activity Add</h1><p class="mt-1 text-sm text-slate-500">Record an activity and optionally schedule a follow-up to-do.</p></div><a href="{{ route('activities.index') }}" class="text-sm font-semibold text-indigo-700">← Activity list</a></div></x-slot>

    <section x-data="activityForm()" class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="bg-gradient-to-r from-[#4165dd] to-[#2947bd] px-6 py-4 text-sm font-bold tracking-wide text-white">ACTIVITY</div>
        <form method="POST" action="{{ route('activities.store') }}" class="p-6 sm:p-8">@csrf
            <input type="hidden" name="subject_id" value="{{ old('subject_id', $defaultSubjectId) }}">
            <div class="grid gap-x-6 gap-y-5 md:grid-cols-2 xl:grid-cols-4">
                <label class="text-sm font-semibold text-slate-700">Type *<select name="activity_type_id" x-model="typeId" @change="loadSubTypes(true)" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select Activity</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(old('activity_type_id') == $type->id)>{{ $type->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('activity_type_id')" class="mt-1"/></label>
                <label class="text-sm font-semibold text-slate-700">Activity Sub Type<select name="activity_sub_type_id" x-model="subTypeId" :disabled="!typeId" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm disabled:bg-slate-100"><option value="" x-text="typeId ? 'Select Activity Sub Type' : 'Select Type First'"></option><template x-for="subType in subTypes" :key="subType.id"><option :value="subType.id" x-text="subType.name"></option></template></select><x-input-error :messages="$errors->get('activity_sub_type_id')" class="mt-1"/></label>
                <label class="text-sm font-semibold text-slate-700">From Date *<input name="from_at" type="datetime-local" value="{{ old('from_at', now()->format('Y-m-d\TH:i')) }}" required class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><x-input-error :messages="$errors->get('from_at')" class="mt-1"/></label>
                <label class="text-sm font-semibold text-slate-700">To Date<input name="to_at" type="datetime-local" value="{{ old('to_at') }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><x-input-error :messages="$errors->get('to_at')" class="mt-1"/></label>

                <label class="text-sm font-semibold text-slate-700">Activity For *<select name="subject_type" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm">@foreach($subjectTypes as $subjectType)<option value="{{ $subjectType->key }}" @selected(old('subject_type', $defaultSubjectType) === $subjectType->key)>{{ $subjectType->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold text-slate-700">Activity with<input name="activity_with" value="{{ old('activity_with') }}" placeholder="Person or organization name" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><x-input-error :messages="$errors->get('activity_with')" class="mt-1"/></label>
                <label class="text-sm font-semibold text-slate-700 xl:col-span-2">Remarks<input name="remarks" value="{{ old('remarks') }}" placeholder="Write a short activity note" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><x-input-error :messages="$errors->get('remarks')" class="mt-1"/></label>
            </div>

            <div class="mt-6 grid gap-5 rounded-lg border border-slate-200 bg-slate-50 p-5 md:grid-cols-2">
                <label class="flex cursor-pointer items-center gap-3 text-sm font-semibold text-slate-700"><input type="checkbox" name="keep_todo" value="1" x-model="keepTodo" class="peer sr-only"><span class="relative h-6 w-11 rounded-full bg-slate-300 transition peer-checked:bg-[#1f7d88] after:absolute after:left-1 after:top-1 after:h-4 after:w-4 after:rounded-full after:bg-white after:transition peer-checked:after:translate-x-5"></span>Keep Todo</label>
                <label class="text-sm font-semibold text-slate-700">Priority<select name="priority" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="low" @selected(old('priority') === 'low')>Low</option><option value="medium" @selected(old('priority', 'medium') === 'medium')>Medium</option><option value="high" @selected(old('priority') === 'high')>High</option></select></label>
            </div>

            <section x-cloak x-show="keepTodo" x-transition class="mt-6 overflow-hidden rounded-lg border border-teal-200 bg-teal-50/30"><div class="bg-[#1f7d88] px-5 py-3 text-sm font-bold text-white">TODO</div><div class="grid gap-5 p-5 md:grid-cols-2 xl:grid-cols-4"><label class="text-sm font-semibold text-slate-700">Type *<select name="todo_type_id" :disabled="!keepTodo" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="">Select</option>@foreach($todoTypes as $todoType)<option value="{{ $todoType->id }}" @selected(old('todo_type_id') == $todoType->id)>{{ $todoType->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('todo_type_id')" class="mt-1"/></label><label class="text-sm font-semibold text-slate-700">Date / Time *<input name="todo_due_at" :disabled="!keepTodo" type="datetime-local" value="{{ old('todo_due_at', now()->format('Y-m-d\TH:i')) }}" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><x-input-error :messages="$errors->get('todo_due_at')" class="mt-1"/></label><label class="text-sm font-semibold text-slate-700">Remind Me Before *<select name="todo_remind_before_minutes" :disabled="!keepTodo" class="mt-2 block w-full rounded-md border-slate-300 py-2.5 text-sm"><option value="0">0 min</option><option value="15" @selected(old('todo_remind_before_minutes') == 15)>15 min</option><option value="30" @selected(old('todo_remind_before_minutes') == 30)>30 min</option><option value="60" @selected(old('todo_remind_before_minutes') == 60)>1 hour</option><option value="1440" @selected(old('todo_remind_before_minutes') == 1440)>1 day</option></select></label><label class="text-sm font-semibold text-slate-700">Todo Note<textarea name="todo_note" :disabled="!keepTodo" rows="2" placeholder="Next action or reminder note" class="mt-2 block w-full rounded-md border-slate-300 text-sm">{{ old('todo_note') }}</textarea></label></div></section>

            <div class="mt-7 flex gap-3 border-t border-slate-100 pt-6"><button class="rounded-md bg-[#1f7d88] px-6 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#176973]">Save</button><a href="{{ route('activities.index') }}" class="rounded-md bg-slate-100 px-6 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-200">Cancel</a></div>
        </form>
    </section>

    <script>function activityForm(){return {typeId:'{{ old('activity_type_id') }}',subTypeId:'{{ old('activity_sub_type_id') }}',keepTodo:@js((bool) old('keep_todo')),subTypes:[],init(){if(this.typeId)this.loadSubTypes()},async loadSubTypes(clear=false){if(clear)this.subTypeId='';this.subTypes=this.typeId?await(await fetch('/crm/activity-types/'+this.typeId+'/sub-types')).json():[]}}}</script>
</x-app-layout>
