<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-xl font-bold text-slate-900">Activity</h1><p class="mt-1 text-sm text-slate-500">Your customer relationship activity history.</p></div><a href="{{ route('activities.create') }}" class="rounded-md bg-[#1f7d88] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#176973]">+ Add activity</a></div>
    </x-slot>
    <form class="mb-5 grid gap-3 rounded-lg border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-5">
        <select name="type" class="rounded-md border-slate-300 py-2.5 text-sm"><option value="">All types</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(($filters['type'] ?? null) == $type->id)>{{ $type->name }}</option>@endforeach</select>
        <select name="user" class="rounded-md border-slate-300 py-2.5 text-sm"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['user'] ?? null) == $user->id)>{{ $user->name }}</option>@endforeach</select>
        <input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="rounded-md border-slate-300 py-2.5 text-sm" aria-label="From date">
        <input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="rounded-md border-slate-300 py-2.5 text-sm" aria-label="To date">
        <div class="flex gap-2"><button class="rounded-md bg-[#1f7d88] px-5 py-2.5 text-sm font-semibold text-white">Search</button><a href="{{ route('activities.index') }}" class="rounded-md border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-600">Reset</a></div>
    </form>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[950px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3.5">SL.</th><th class="px-4 py-3.5">Date &amp; time</th><th class="px-4 py-3.5">User</th><th class="px-4 py-3.5">Activity type</th><th class="px-4 py-3.5">With</th><th class="px-4 py-3.5">For</th><th class="px-4 py-3.5">Remarks</th><th class="px-4 py-3.5">Attachment</th><th class="px-4 py-3.5"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($activities as $activity)<tr class="hover:bg-slate-50"><td class="px-4 py-4">{{ $activities->firstItem() + $loop->index }}</td><td class="whitespace-nowrap px-4 py-4">{{ $activity->from_at->format('d-m-y h:i A') }}</td><td class="px-4 py-4">{{ $activity->user->name }}</td><td class="px-4 py-4"><p class="font-semibold text-slate-800">{{ $activity->type->name }}</p><p class="mt-0.5 text-xs text-slate-400">{{ $activity->subType?->name }}</p></td><td class="px-4 py-4">{{ $activity->activity_with ?: '—' }}</td><td class="px-4 py-4 capitalize">{{ $activity->subject_type }}</td><td class="max-w-xs px-4 py-4 text-slate-600">{{ $activity->remarks ?: '—' }}</td><td class="px-4 py-4">@if($activity->attachment_path)<a href="{{ Storage::disk('public')->url($activity->attachment_path) }}" target="_blank" class="font-medium text-indigo-700 hover:underline">View image</a>@else<span class="text-slate-400">—</span>@endif</td><td class="px-4 py-4"><form method="POST" action="{{ route('activities.destroy', $activity) }}" onsubmit="return confirm('Delete this activity?')">@csrf @method('DELETE')<button class="text-slate-400 hover:text-rose-600" title="Delete activity">✕</button></form></td></tr>@empty<tr><td colspan="9" class="px-5 py-14 text-center text-slate-500">No activities found. Add your first customer interaction.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 px-5 py-4">{{ $activities->links() }}</div></section>
</x-app-layout>
